# ============================================================
#  nwa - network diagnostics for Windows
#
#  Run it, watch the live status, press Q to stop - it builds
#  and opens an HTML report. The raw log (network-monitor.jsonl)
#  is written continuously, so nothing is lost on a crash.
#  Nothing is uploaded by this script; analysis is local.
#
#  Usage:
#    powershell -ep bypass -f .\nwa.ps1                    monitor until Q
#    powershell -ep bypass -f .\nwa.ps1 -Snapshot          one-shot check
#    powershell -ep bypass -f .\nwa.ps1 -Sites "a.com"     also test your sites
#
#  This file is generated by build.ps1 from src/nwa.src.ps1
#  plus index.html (the embedded report template). Edit src/,
#  then run build.ps1.
# ============================================================
param(
  [switch]$Snapshot,                 # one-shot health check instead of monitoring
  [string[]]$Sites = @(),            # extra sites to test, e.g. -Sites "yourapp.com","intranet.local"
  [switch]$M365,                     # also test Microsoft 365 reachability (sign-in, Teams, Outlook)
  [int]$SiteCheckSec = 60,           # how often to test sites (they are far slower than a ping)
  [int]$IntervalSec = 10,            # seconds between checks
  [double]$DurationHours = 0,        # 0 = run until Q / Ctrl+C
  [int]$PingCount = 5,               # pings per target per check (loss / jitter)
  [int]$NeighborScanSec = 300,       # how often to scan nearby APs (0 = never)
  [string]$OutDir = '',              # where files go (default: %LOCALAPPDATA%\nwa)
  [string]$RunLabel = '',            # e.g. baseline, post-AP-change, validation
  [string]$OfficeHours = '08-17',    # when the place is busy, for the report's coverage check
  [switch]$IncludePublicIp           # snapshot only; makes a request to api.ipify.org
)

$ErrorActionPreference = 'SilentlyContinue'
$ProgressPreference    = 'SilentlyContinue'
$script:ToolVersion    = '0.1.0'

# make sure the Windows networking modules (NetAdapter, DnsClient) are findable
$winMods = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\Modules'
if ((Test-Path $winMods) -and ($env:PSModulePath -notlike ('*' + $winMods + '*'))) { $env:PSModulePath += ';' + $winMods }
$script:hasResolve = [bool](Get-Command Resolve-DnsName -ErrorAction SilentlyContinue)

# Embedded report template: base64 of index.html from this repo (see build.ps1).
# It is only ever written to an .html file - never executed as code.
$NWA_B64 = '@@NWA_TEMPLATE_B64@@'

# Everything lands in one out-of-the-way folder and the report opens by itself,
# so nothing clutters the desktop. The log is appended every few seconds, so this
# folder must not be inside OneDrive or Dropbox.
if ($OutDir) { $LogDir = $OutDir } else { $LogDir = Join-Path $env:LOCALAPPDATA 'nwa' }
$ReportDir = $LogDir
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

# Office hours ("08-17") travel with the log so the report can judge whether a run
# actually covered a busy office.
$officeStart = 8; $officeEnd = 17
if ($OfficeHours -match '^\s*(\d{1,2})\s*-\s*(\d{1,2})\s*$') { $officeStart = [int]$matches[1]; $officeEnd = [int]$matches[2] }
else { Write-Host "Could not read -OfficeHours '$OfficeHours' - using 08-17." -ForegroundColor DarkYellow }
# Every capture gets its own stable ID. This preserves evidence for before/after
# comparisons instead of overwriting the previous monitor log and report.
$script:runId = (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ') + '-' + ([guid]::NewGuid().ToString('N').Substring(0,6))
# every line written to the log is also kept in memory; the report is built from
# memory so a sync engine mangling the log file cannot produce an empty report
$script:logLines = New-Object System.Collections.Generic.List[string]

$targets = @('1.1.1.1','8.8.8.8')
$dnsHost = 'google.com'
# Opt-in, not default: a general network tool should not start probing Microsoft
# on someone else's machine unasked, and plenty of places do not use 365 at all.
#
# Worth knowing what these do and do not tell you. They measure the web front
# door - reachable, and how far away. Teams *calls* run over UDP to a media relay
# on entirely different endpoints, so a good number here is not proof that audio
# is fine. What it is good for: sign-in gates every 365 service, so if that is
# slow everything feels slow; and comparing the same endpoint from two machines
# tells you whether a slow service is your network or just where it is hosted.
$M365Sites = @('login.microsoftonline.com','teams.microsoft.com','outlook.office365.com')
$siteList = @()
if ($M365) { $siteList += $M365Sites }
$siteList += $Sites
$httpTargets = @(foreach ($s in $siteList) { $s = [string]$s; $s = $s.Trim(); if ($s) { if ($s -match '^https?://') { $s } else { 'https://' + $s } } })
$httpTargets = @($httpTargets | Select-Object -Unique)

# ---------- helpers ----------

# fast multi-ping (no 1s gap) - returns recv/loss/min/avg/max/jitter
function Test-PingSet([string]$ip,[int]$count,[int]$timeoutMs){
  $rtts = New-Object System.Collections.Generic.List[int]
  $pinger = New-Object System.Net.NetworkInformation.Ping
  for ($i=0; $i -lt $count; $i++) {
    try { $pr = $pinger.Send($ip,$timeoutMs); if ($pr.Status -eq 'Success') { $rtts.Add([int]$pr.RoundtripTime) } } catch {}
  }
  $recv = $rtts.Count
  $o = [ordered]@{ recv=$recv; loss=[math]::Round((1-($recv/$count))*100,0); min=$null; avg=$null; max=$null; jit=$null }
  if ($recv -gt 0) {
    $o.min = ($rtts | Measure-Object -Minimum).Minimum
    $o.max = ($rtts | Measure-Object -Maximum).Maximum
    $o.avg = [math]::Round(($rtts | Measure-Object -Average).Average,0)
    if ($rtts.Count -gt 1) {
      $d = New-Object System.Collections.Generic.List[int]
      for ($i=1; $i -lt $rtts.Count; $i++) { $d.Add([math]::Abs($rtts[$i]-$rtts[$i-1])) }
      $o.jit = [math]::Round(($d | Measure-Object -Average).Average,0)
    } else { $o.jit = 0 }
  }
  return $o
}

# current Wi-Fi association (ssid, bssid, signal, band, channel, rates)
function Get-WlanInfo {
  $w = [ordered]@{ ssid=$null; sig=$null; bssid=$null; band=$null; chan=$null; rx=$null; tx=$null; radio=$null }
  foreach ($l in (netsh wlan show interfaces)) {
    if     ($l -match '^\s*SSID\s+:\s*(.+)$')                    { $w.ssid=$matches[1].Trim() }
    elseif ($l -match '^\s*Signal\s*:\s*(\d+)%')                 { $w.sig=[int]$matches[1] }
    elseif ($l -match 'BSSID\s*:\s*([0-9a-fA-F:]{17})')          { $w.bssid=$matches[1].Trim() }
    elseif ($l -match '^\s*Band\s*:\s*(.+)$')                    { $w.band=$matches[1].Trim() }
    elseif ($l -match '^\s*Channel\s*:\s*(\d+)')                 { $w.chan=[int]$matches[1] }
    elseif ($l -match '^\s*Receive rate \(Mbps\)\s*:\s*([\d\.]+)'){ $w.rx=[double]$matches[1] }
    elseif ($l -match '^\s*Transmit rate \(Mbps\)\s*:\s*([\d\.]+)'){ $w.tx=[double]$matches[1] }
    elseif ($l -match '^\s*Radio type\s*:\s*(.+)$')              { $w.radio=$matches[1].Trim() }
  }
  return $w
}

# scan nearby Wi-Fi networks -> how crowded is my channel
function Get-Congestion([int]$myChan){
  $chans = New-Object System.Collections.Generic.List[int]
  foreach ($l in (netsh wlan show networks mode=bssid)) {
    if ($l -match '^\s*Channel\s*:\s*(\d+)') { $chans.Add([int]$matches[1]) }
  }
  [ordered]@{ total = $chans.Count; coChan = @($chans | Where-Object { $_ -eq $myChan }).Count; chan = $myChan }
}

# new Windows Wi-Fi events since last check (connect / fail / disconnect + reason)
$script:lastSiteCheck = [datetime]::MinValue
$script:wlanLogOk = $true
$script:wlanSeen  = New-Object System.Collections.Generic.HashSet[long]
function Get-WlanEvents([datetime]$since){
  if (-not $script:wlanLogOk) { return @() }
  $out = @()
  try {
    $evs = Get-WinEvent -FilterHashtable @{
      LogName='Microsoft-Windows-WLAN-AutoConfig/Operational'
      Id=@(8001,8002,8003)
      StartTime=$since.AddSeconds(-5)
    } -ErrorAction Stop
    foreach ($e in $evs) {
      if (-not $script:wlanSeen.Add([long]$e.RecordId)) { continue }
      $msg = ''
      if ($e.Id -eq 8003) {
        $msg = 'disconnect'
        if ($e.Message -match 'Reason:\s*(.+)') { $msg = 'disconnect: ' + $matches[1].Trim() }
      } elseif ($e.Id -eq 8001) { $msg = 'connected' }
      elseif ($e.Id -eq 8002)   { $msg = 'connection failed' }
      $out += [ordered]@{ t=$e.TimeCreated.ToString('o'); id=$e.Id; msg=$msg }
    }
    if ($script:wlanSeen.Count -gt 500) { $script:wlanSeen.Clear() }
  } catch {
    if ($_.FullyQualifiedErrorId -notmatch 'NoMatchingEvents') { $script:wlanLogOk = $false }
  }
  return @($out | Sort-Object t)
}

# short TTL-stepped trace: where does the path die? (bounded, ~4s worst case)
function Invoke-QuickTrace([string]$dest,[int]$maxHops){
  $hops = @()
  $p = New-Object System.Net.NetworkInformation.Ping
  $buf = New-Object byte[] 8
  for ($ttl=1; $ttl -le $maxHops; $ttl++) {
    try {
      $opt = New-Object System.Net.NetworkInformation.PingOptions($ttl,$true)
      $r = $p.Send($dest,700,$buf,$opt)
      if ($r.Status -eq 'Success')        { $hops += $r.Address.ToString(); break }
      elseif ($r.Status -eq 'TtlExpired') { $hops += $r.Address.ToString() }
      else                                { $hops += '*' }
    } catch { $hops += '*' }
  }
  return $hops
}

# wired adapter link speed in Mbps (catches 1000 -> 100 renegotiation)
# Only the adapter actually carrying the default route counts as "wired". Taking
# the first non-wireless adapter that happens to be Up reports Hyper-V switches,
# WSL, VPN and dock adapters as a wired link - they sit at "Up" forever and
# report 1 or 10 Gbps, so a laptop on Wi-Fi claimed a 10 Gbps cable.
function Get-EthMbps($upAdapters, $routeIfIndex){
  if ($null -eq $routeIfIndex) { return $null }
  $e = $upAdapters | Where-Object {
        $_.ifIndex -eq $routeIfIndex -and $_.PhysicalMediaType -notmatch '802.11|Wireless'
      } | Select-Object -First 1
  if (-not $e) { return $null }
  if ($e.LinkSpeed -match '([\d\.]+)\s*(G|M)bps') {
    $v = [double]$matches[1]; if ($matches[2] -eq 'G') { $v = $v * 1000 }
    return [int]$v
  }
  return $null
}

# HTTP(S) reachability. ms = -1 means could not reach at all; any status code counts as reached.
function Test-Sites([string[]]$urls){
  @(foreach ($u in $urls) {
    $hsw = [System.Diagnostics.Stopwatch]::StartNew()
    try {
      $resp = Invoke-WebRequest -Uri $u -Method Head -TimeoutSec 6 -UseBasicParsing -ErrorAction Stop
      $hsw.Stop()
      [ordered]@{ u = $u; ms = [int]$hsw.Elapsed.TotalMilliseconds; code = [int]$resp.StatusCode }
    } catch {
      $hsw.Stop()
      $code = 0
      if ($_.Exception.Response) { try { $code = [int]$_.Exception.Response.StatusCode } catch {} }
      if ($code -gt 0) { [ordered]@{ u = $u; ms = [int]$hsw.Elapsed.TotalMilliseconds; code = $code } }
      else             { [ordered]@{ u = $u; ms = -1; code = 0 } }
    }
  })
}

# build network-report.html from the in-memory data lines (never re-reads the log file)
function New-NwaReport([string[]]$jsonLines,[bool]$OpenIt,[string]$runId){
  if ($NWA_B64 -like '@@*') { Write-Host 'No report template embedded (source build) - run build.ps1 first.' -ForegroundColor DarkYellow; return $null }
  if (-not $jsonLines -or $jsonLines.Count -eq 0) { Write-Host 'No data captured - report skipped.' -ForegroundColor DarkYellow; return $null }
  try {
    $tpl = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($NWA_B64))
    $arr = '[' + ($jsonLines -join ',') + ']'
    $arr = $arr.Replace('</','<\/')   # keep '</script>' inside logged strings from breaking the page
    $html = $tpl.Replace('window.NWA_EMBEDDED = window.NWA_EMBEDDED || null;', 'window.NWA_EMBEDDED = ' + $arr + ';')
    $rp = Join-Path $ReportDir ('network-report-' + $runId + '.html')
    Set-Content -Path $rp -Value $html -Encoding utf8
    Write-Host ('Report: ' + $rp) -ForegroundColor Green
    if ($OpenIt) { Start-Process $rp }
    return $rp
  } catch { Write-Host ('Could not build report: ' + $_) -ForegroundColor Red; return $null }
}

# ---------- environment context (collected once) ----------

$activeRoute = $null
$gateway = $null
try {
  # Prefer the actual lowest-metric IPv4 default route over an arbitrary
  # "first" adapter. This matters when Wi-Fi, Ethernet, and a VPN coexist.
  $r = Get-NetRoute -DestinationPrefix '0.0.0.0/0' -ErrorAction Stop |
    Where-Object { $_.NextHop -and $_.NextHop -ne '0.0.0.0' } |
    Sort-Object @{ Expression = { [int]$_.RouteMetric + [int]$_.InterfaceMetric } }, RouteMetric |
    Select-Object -First 1
  if ($r) {
    $gateway = [string]$r.NextHop
    $routeAdapter = Get-NetAdapter -InterfaceIndex $r.InterfaceIndex -ErrorAction SilentlyContinue
    $activeRoute = [ordered]@{
      ifIndex = [int]$r.InterfaceIndex
      alias = if ($routeAdapter) { [string]$routeAdapter.Name } else { $null }
      nextHop = $gateway
      metric = [int]$r.RouteMetric + [int]$r.InterfaceMetric
    }
  }
} catch {}
if (-not $gateway) {
  try { $gateway = (Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway } | Select-Object -First 1).IPv4DefaultGateway.NextHop } catch {}
}

$upIdx = @((Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }).ifIndex)
$dnsIdx = if ($activeRoute) { @($activeRoute.ifIndex) } else { $upIdx }
$dnsServers = @(Get-DnsClientServerAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
  Where-Object { $_.ServerAddresses -and ($dnsIdx -contains $_.InterfaceIndex) } |
  ForEach-Object { $_.ServerAddresses } | Select-Object -Unique)

# A DNS answer only proves the internet is reachable when the resolver is off-LAN.
# On a domain-joined PC the resolver is usually an on-prem DC, which keeps answering
# from the LAN during an internet outage - so it cannot be used as proof of uptime.
function Test-OffLanAddress([string]$ip){
  if (-not $ip) { return $false }
  if ($ip -notmatch '^\d{1,3}(\.\d{1,3}){3}$') { return $false }
  $o = $ip.Split('.') | ForEach-Object { [int]$_ }
  if ($o[0] -eq 10) { return $false }
  if ($o[0] -eq 127) { return $false }
  if ($o[0] -eq 172 -and $o[1] -ge 16 -and $o[1] -le 31) { return $false }
  if ($o[0] -eq 192 -and $o[1] -eq 168) { return $false }
  if ($o[0] -eq 169 -and $o[1] -eq 254) { return $false }
  if ($o[0] -eq 100 -and $o[1] -ge 64 -and $o[1] -le 127) { return $false }   # CGNAT
  return $true
}
# Conservative: every configured resolver must be off-LAN, because Windows may use any of them.
$dnsIsPublic = ($dnsServers.Count -gt 0) -and -not (@($dnsServers | Where-Object { -not (Test-OffLanAddress $_) }).Count)
if (-not $dnsIsPublic) {
  Write-Host 'DNS resolver is on the local network - ICMP failures will be treated as real outages.' -ForegroundColor DarkYellow
}
if ($gateway) {
  $gwTest = Test-PingSet $gateway 2 800
  if ($gwTest.recv -eq 0) { Write-Host "Gateway $gateway doesn't answer ping (ICMP blocked) - skipping gateway checks." -ForegroundColor DarkYellow; $gateway = $null }
}

# adapter + driver + power management (radio power saving is a common cause of drops)
$adapterInfo = $null
try {
  $a = Get-NetAdapter -ErrorAction Stop | Where-Object { $_.Status -eq 'Up' } |
       Sort-Object { if ($activeRoute -and $_.ifIndex -eq $activeRoute.ifIndex) { 0 } elseif ($_.PhysicalMediaType -match '802.11|Wireless') { 1 } else { 2 } } |
       Select-Object -First 1
  if ($a) {
    $pm = $null
    try { $p = Get-NetAdapterPowerManagement -Name $a.Name -ErrorAction Stop
          if ($p) { $pm = [ordered]@{ selectiveSuspend = [string]$p.SelectiveSuspend; sleepOnDisconnect = [string]$p.DeviceSleepOnDisconnect } } } catch {}
    $adapterInfo = [ordered]@{
      name = $a.Name; description = $a.InterfaceDescription
      driverVersion = [string]$a.DriverVersion; driverDate = [string]$a.DriverDate
      linkSpeed = [string]$a.LinkSpeed; powerMgmt = $pm
    }
  }
} catch {}

# IPv6 reachability (context)
$ipv6 = $null
try { $r6 = Test-PingSet '2606:4700:4700::1111' 2 1200; $ipv6 = [ordered]@{ reachable = ($r6.recv -gt 0); ms = $r6.avg } }
catch { $ipv6 = [ordered]@{ reachable = $false; ms = $null } }

# Windows 11 24H2 hides BSSID / neighbor networks when Location is off
$w0 = Get-WlanInfo
$bssidHidden = $false
if ($w0.sig -ne $null -and -not $w0.bssid) {
  $bssidHidden = $true
  Write-Host 'Windows is hiding the AP identity (Location is off?) - roam detection will be limited.' -ForegroundColor DarkYellow
  Write-Host 'Enable Settings > Privacy & security > Location to get full Wi-Fi detail.' -ForegroundColor DarkYellow
}

# ============================================================
#  SNAPSHOT MODE
# ============================================================
if ($Snapshot) {
  $snapData = [ordered]@{}
  $snapData.schema      = 'nwa-report/1'
  $snapData.toolVersion = $script:ToolVersion
  $snapData.runId       = $script:runId
  $snapData.runLabel    = $RunLabel
  $snapData.officeHours = ($officeStart.ToString("00") + "-" + $officeEnd.ToString("00"))
  $snapData.generatedAt = (Get-Date).ToString('o')
  $snapData.hoursWindow = 24

  Write-Host 'Collecting system info...'
  $os = Get-CimInstance Win32_OperatingSystem
  $snapData.system = [ordered]@{
    computerName = $env:COMPUTERNAME
    user         = $env:USERNAME
    os           = $os.Caption
    osVersion    = [string]$os.Version
    uptimeHours  = [math]::Round(((Get-Date) - $os.LastBootUpTime).TotalHours, 1)
  }

  Write-Host 'Collecting network adapters...'
  $snapData.adapters = @(Get-NetAdapter | ForEach-Object {
    [ordered]@{
      name        = $_.Name
      description = $_.InterfaceDescription
      status      = [string]$_.Status
      macAddress  = $_.MacAddress
      linkSpeed   = $_.LinkSpeed
      mediaType   = [string]$_.PhysicalMediaType
      ifIndex     = $_.ifIndex
    }
  })

  Write-Host 'Collecting IP configuration...'
  $snapData.ipConfig = @(Get-NetIPConfiguration | ForEach-Object {
    [ordered]@{
      alias   = $_.InterfaceAlias
      ipv4    = [string]$_.IPv4Address.IPAddress
      ipv6    = [string]$_.IPv6Address.IPAddress
      gateway = [string]$_.IPv4DefaultGateway.NextHop
    }
  })

  $snapData.dns = @(Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object { $_.ServerAddresses } | ForEach-Object {
    [ordered]@{ alias = $_.InterfaceAlias; servers = @($_.ServerAddresses) }
  })

  Write-Host 'Collecting adapter traffic counters...'
  $snapData.adapterStats = @(Get-NetAdapterStatistics | ForEach-Object {
    [ordered]@{
      name                   = $_.Name
      receivedBytes          = [int64]$_.ReceivedBytes
      sentBytes              = [int64]$_.SentBytes
      receivedUnicastPackets = [int64]$_.ReceivedUnicastPackets
      sentUnicastPackets     = [int64]$_.SentUnicastPackets
    }
  })

  Write-Host 'Collecting Wi-Fi state...'
  $snapData.wifi = [ordered]@{}
  $wifiRaw = netsh wlan show interfaces
  if ($wifiRaw) {
    $snapData.wifi.raw = ($wifiRaw -join "`n")
    foreach ($line in $wifiRaw) {
      if ($line -match '^\s*(SSID|BSSID|Signal|Channel|Band|Radio type|Receive rate \(Mbps\)|Transmit rate \(Mbps\)|Authentication|State)\s*:\s*(.+)$') {
        $snapData.wifi[$matches[1].Trim()] = $matches[2].Trim()
      }
    }
  }

  Write-Host 'Running latency tests...'
  $snapData.latency = @(foreach ($t in @('1.1.1.1','8.8.8.8','google.com')) {
    $r = Test-PingSet $t 4 1200
    [ordered]@{
      target   = $t
      sent     = 4
      received = $r.recv
      lossPct  = $r.loss
      avgMs    = $r.avg
      minMs    = $r.min
      maxMs    = $r.max
    }
  })

  Write-Host 'Testing DNS resolution speed...'
  $snapData.dnsTest = @(foreach ($h in @('google.com','cloudflare.com','microsoft.com')) {
    $sw  = [System.Diagnostics.Stopwatch]::StartNew()
    $res = Resolve-DnsName -Name $h -Type A -DnsOnly -ErrorAction SilentlyContinue
    $sw.Stop()
    [ordered]@{
      host      = $h
      ms        = [math]::Round($sw.Elapsed.TotalMilliseconds, 0)
      resolved  = [bool]$res
      addresses = @($res | Where-Object { $_.IPAddress } | ForEach-Object { $_.IPAddress })
    }
  })

  Write-Host 'Collecting active connections...'
  $procs = @{}
  Get-Process | ForEach-Object { $procs[$_.Id] = $_.ProcessName }
  $snapData.connections = @(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{
      localAddress  = $_.LocalAddress
      localPort     = $_.LocalPort
      remoteAddress = $_.RemoteAddress
      remotePort    = $_.RemotePort
      process       = $procs[[int]$_.OwningProcess]
      pid           = $_.OwningProcess
    }
  } | Select-Object -First 250)

  Write-Host 'Collecting listening ports...'
  $snapData.listening = @(Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{
      localAddress = $_.LocalAddress
      localPort    = $_.LocalPort
      process      = $procs[[int]$_.OwningProcess]
      pid          = $_.OwningProcess
    }
  } | Select-Object -First 150)

  $snapData.routes = @(Get-NetRoute -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{ ifAlias = $_.InterfaceAlias; nextHop = $_.NextHop; metric = $_.RouteMetric }
  })

  $snapData.publicIpCollected = [bool]$IncludePublicIp
  if ($IncludePublicIp) {
    Write-Host 'Looking up public IP (best effort)...'
    try   { $snapData.publicIp = (Invoke-RestMethod -Uri 'https://api.ipify.org?format=json' -TimeoutSec 5).ip }
    catch { $snapData.publicIp = $null }
  } else { $snapData.publicIp = $null }

  Write-Host 'Collecting recent network events (last 24h)...'
  $since = (Get-Date).AddHours(-24)
  $snapData.events = @(Get-WinEvent -FilterHashtable @{ LogName = 'System'; StartTime = $since } -ErrorAction SilentlyContinue |
    Where-Object { $_.ProviderName -match 'Tcpip|Dhcp|WLAN|NetworkProfile|Netwtw|NDIS|Wlansvc|Dnscache' } |
    Select-Object -First 300 | ForEach-Object {
      [ordered]@{
        time     = $_.TimeCreated.ToString('o')
        level    = [string]$_.LevelDisplayName
        provider = $_.ProviderName
        id       = $_.Id
        message  = ($_.Message -replace '\s+', ' ').Trim()
      }
    })

  $outPath = Join-Path $LogDir ('network-report-' + $script:runId + '.json')
  $snapData | ConvertTo-Json -Depth 8 | Out-File -FilePath $outPath -Encoding utf8
  Write-Host ('Data: ' + $outPath) -ForegroundColor Green
  $interactive = $true
  try { $interactive = ($Host.Name -eq 'ConsoleHost') -and -not [Console]::IsInputRedirected } catch { $interactive = $false }
  $compact = $snapData | ConvertTo-Json -Compress -Depth 8
  New-NwaReport @($compact) $interactive $script:runId | Out-Null
  return
}

# ============================================================
#  MONITOR MODE
# ============================================================
$out = Join-Path $LogDir ('network-monitor-' + $script:runId + '.jsonl')

$meta = [ordered]@{
  schema          = 'nwa-monitor/1'
  toolVersion     = $script:ToolVersion
  runId           = $script:runId
  runLabel        = $RunLabel
  officeHours     = ($officeStart.ToString("00") + "-" + $officeEnd.ToString("00"))
  startedAt       = (Get-Date).ToString('o')
  intervalSec     = $IntervalSec
  durationHours   = $DurationHours
  pingCount       = $PingCount
  neighborScanSec = $NeighborScanSec
  computerName    = $env:COMPUTERNAME
  targets         = $targets
  gateway         = $gateway
  activeRoute     = $activeRoute
  dnsHost         = $dnsHost
  dnsServers      = $dnsServers
  dnsIsPublic     = $dnsIsPublic
  adapter         = $adapterInfo
  ipv6            = $ipv6
  bssidHidden     = $bssidHidden
  httpTargets     = $httpTargets
}
$metaJson = $meta | ConvertTo-Json -Compress
$script:logLines.Add($metaJson)
Set-Content -Path $out -Value $metaJson -Encoding utf8

$interactive = $true
try { $interactive = ($Host.Name -eq 'ConsoleHost') -and -not [Console]::IsInputRedirected } catch { $interactive = $false }

$end = (Get-Date).AddHours($DurationHours)
$stopMsg = if ($DurationHours -le 0) { 'until you press Q' } else { "until $end (or Q)" }
if (-not $interactive) { $stopMsg = if ($DurationHours -le 0) { 'until Ctrl+C' } else { "until $end" } }

# ---------- session state ----------
$nbrEvery  = if ($NeighborScanSec -gt 0) { [math]::Max(1, [int]($NeighborScanSec / $IntervalSec)) } else { 0 }
$k = 0
$stopReq = $false
$startT = Get-Date
$stLastEvT = Get-Date
$stRoams = 0; $stAps = New-Object System.Collections.Generic.HashSet[string]
$stOutages = 0; $stDownSec = 0; $stWasDown = $false
$stLoss = 0; $stJit = 0; $stDnsFail = 0
$stEvents = New-Object System.Collections.Generic.List[string]
$stHist = ''
$stLastTrace = [datetime]::MinValue
$script:dashDrawn = $false
$script:lastRows = 0

function Format-Elapsed([timespan]$ts){
  if ($ts.TotalHours -ge 1) { return ('{0}h {1:d2}m' -f [int][math]::Floor($ts.TotalHours), $ts.Minutes) }
  return ('{0:d2}:{1:d2}' -f $ts.Minutes, $ts.Seconds)
}
function Add-Ev([string]$s){ $stEvents.Add($s); while ($stEvents.Count -gt 3) { $stEvents.RemoveAt(0) } }

# --- dashboard rendering ---
# One rounded panel with a legend tab, muted labels down the left, and enough
# motion that the thing reads as alive between samples. The source stays ASCII:
# every box-drawing glyph goes in as a [char] code point, because a stray
# non-ASCII byte in this file stops Windows PowerShell parsing it at all.

$E = [char]27
$script:RST = $E + '[0m'
$script:EL  = $E + '[K'
$script:frame = 0

# Truecolour and box drawing need a terminal that processes VT sequences.
# Windows Terminal and PowerShell 7 both do; older consoles get an ASCII panel
# in the 16 console colours instead, which is why every row is built as
# (text, token) segments rather than as pre-coloured strings.
$script:Fancy = $false
if ($env:WT_SESSION) { $script:Fancy = $true }
elseif ($PSVersionTable.PSVersion.Major -ge 7) { $script:Fancy = $true }
if ($env:NWA_PLAIN) { $script:Fancy = $false }
if ($script:Fancy) {
  # Consoles often default to an OEM code page, which draws the rounded corners
  # and the braille spinner as '?'. Without UTF-8 the panel falls apart.
  try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch { $script:Fancy = $false }
}

# One palette, same token names as the report's CSS custom properties, so the
# terminal and the HTML cannot drift into looking like two different tools.
$script:Pal = @{
  accent    = @(111,143,214); accentHi = @(157,180,234); accentDim = @(70,88,127)
  fg        = @(232,232,242); dim      = @(166,166,184); muted     = @(111,111,128)
  ok        = @(91,192,143);  warn     = @(211,160,90);  bad       = @(224,112,112)
}
$script:PalC = @{
  accent='Blue'; accentHi='Cyan'; accentDim='DarkBlue'
  fg='White'; dim='Gray'; muted='DarkGray'
  ok='Green'; warn='Yellow'; bad='Red'
}

if ($script:Fancy) {
  $script:G = @{
    tl=[string][char]0x256D; tr=[string][char]0x256E; bl=[string][char]0x2570; br=[string][char]0x256F
    h=[string][char]0x2500;  v=[string][char]0x2502;  ml=[string][char]0x251C; mr=[string][char]0x2524
    dot=[string][char]0x00B7; bar=[string][char]0x2501; barDim=[string][char]0x2500; ell=[string][char]0x2026
  }
  $script:Spin = @([char]0x280B,[char]0x2819,[char]0x2839,[char]0x2838,[char]0x283C,
                   [char]0x2834,[char]0x2826,[char]0x2827,[char]0x2807,[char]0x280F)
} else {
  $script:G = @{ tl='+'; tr='+'; bl='+'; br='+'; h='-'; v='|'; ml='+'; mr='+'
                 dot='-'; bar='='; barDim='-'; ell='...' }
  $script:Spin = @('|','/','-','\')
}

function Rgb([int]$r,[int]$g,[int]$b){ return ($E + '[38;2;' + $r + ';' + $g + ';' + $b + 'm') }
function TokAnsi($tok){
  if ($tok -is [array]) { return (Rgb $tok[0] $tok[1] $tok[2]) }
  $c = $script:Pal[[string]$tok]; if (-not $c) { $c = $script:Pal['fg'] }
  return (Rgb $c[0] $c[1] $c[2])
}
function TokCon($tok){
  if ($tok -is [array]) { return 'Cyan' }
  $c = $script:PalC[[string]$tok]; if (-not $c) { $c = 'Gray' }
  return $c
}
function SegLen($row){ $n=0; foreach($s in $row){ $n += ([string]$s[0]).Length }; return $n }

# Every row is written at an absolute cursor position with no trailing newline.
# Letting lines flow naturally scrolls the buffer the moment the panel is as
# tall as the window, and the next frame then draws into a shifted view - which
# is what made the whole screen jump.
function Emit-Row($row,[int]$w,[int]$line){
  $wh = 200; try { $wh = [Console]::WindowHeight } catch {}
  if ($line -ge $wh) { return }
  if ($script:Fancy) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append($E + '[' + ($line + 1) + ';1H')
    foreach($s in $row){ [void]$sb.Append((TokAnsi $s[1])); [void]$sb.Append([string]$s[0]) }
    [void]$sb.Append($script:RST); [void]$sb.Append($script:EL)
    [Console]::Write($sb.ToString())
  } else {
    try { [Console]::SetCursorPosition(0, $line) } catch { return }
    $len = 0
    foreach($s in $row){
      Write-Host ([string]$s[0]) -NoNewline -ForegroundColor (TokCon $s[1])
      $len += ([string]$s[0]).Length
    }
    if($len -lt $w){ Write-Host (' ' * ($w - $len)) -NoNewline }
  }
}

function DashW {
  $c = 100; try { $c = [Console]::WindowWidth } catch {}
  if ($c -lt 60) { $c = 60 }
  return [math]::Min($c - 4, 118)
}
function Clip([string]$s,[int]$n){
  if ($null -eq $s) { return '' }
  $s = ($s -replace '[\r\n\t]',' ')
  if ($s.Length -gt $n) { return $s.Substring(0,[math]::Max(0,$n-1)) + $script:G.ell }
  return $s
}

# --- brand ---------------------------------------------------------------
$script:NwaLogo = @(
  ' _  _ __      ___   ',
  '| \| |\ \    / /_\  ',
  '| .` | \ \/\/ / _ \ ',
  '|_|\_|  \_/\_/_/ \_\'
)
$script:NwaTag = 'network analysis'

# A highlight sweeps left to right across the letters, like a trace crossing a
# scope. Runs of equal colour are merged so a frame is a handful of escape
# sequences rather than one per character.
function Banner-Rows([string]$hostName){
  $lw = 0; foreach($l in $script:NwaLogo){ if($l.Length -gt $lw){ $lw = $l.Length } }
  $span = $lw + 18
  $head = ($script:frame * 3) % $span
  $out = New-Object System.Collections.Generic.List[object]
  for($i=0; $i -lt $script:NwaLogo.Count; $i++){
    $line = $script:NwaLogo[$i]
    $row = New-Object System.Collections.Generic.List[object]
    $row.Add(@('  ','muted'))
    if ($script:Fancy) {
      $cur = ''; $curTok = $null
      for($x=0; $x -lt $line.Length; $x++){
        $d = $head - $x
        $tok = 'accentDim'
        if ($d -eq 0 -or $d -eq 1) { $tok = @(200,216,250) }
        elseif ($d -eq 2) { $tok = 'accentHi' }
        elseif ($d -eq 3 -or $d -eq 4) { $tok = 'accent' }
        if ($null -ne $curTok -and (($tok -is [array]) -ne ($curTok -is [array]) -or ("$tok" -ne "$curTok"))) {
          $row.Add(@($cur,$curTok)); $cur = ''
        }
        $cur += $line[$x]; $curTok = $tok
      }
      if ($cur) { $row.Add(@($cur,$curTok)) }
    } else {
      $row.Add(@($line,'accent'))
    }
    if ($i -eq 1) { $row.Add(@(('   ' + $script:NwaTag),'muted')) }
    if ($i -eq 2) { $row.Add(@(('   ' + $hostName),'fg')) }
    $out.Add($row)
  }
  return ,$out
}

# --- panel ---------------------------------------------------------------
function P-Top([string]$legend,[int]$w){
  $row = New-Object System.Collections.Generic.List[object]
  $sp = [string]$script:Spin[$script:frame % $script:Spin.Count]
  $row.Add(@(('  ' + $script:G.tl + $script:G.h + ' '),'accent'))
  $row.Add(@(($sp + ' '),'accentHi'))
  $row.Add(@($legend,'fg'))
  $used = 4 + 2 + $legend.Length + 1
  $dash = $w - $used - 1; if($dash -lt 0){ $dash = 0 }
  $row.Add(@((' ' + ($script:G.h * $dash) + $script:G.tr),'accent'))
  return ,$row
}
function P-Rule([int]$w){
  $row = New-Object System.Collections.Generic.List[object]
  $row.Add(@(('  ' + $script:G.ml + ($script:G.h * ($w - 3)) + $script:G.mr),'accent'))
  return ,$row
}
function P-Bot([int]$w){
  $row = New-Object System.Collections.Generic.List[object]
  $row.Add(@(('  ' + $script:G.bl + ($script:G.h * ($w - 3)) + $script:G.br),'accent'))
  return ,$row
}
# label on the left in muted, then whatever segments the caller wants, padded
# out so the right-hand rule always lands in the same column. Segments that
# would run past the border are clipped rather than pushing it out of line.
function P-Row([string]$label,$segs,[int]$w){
  $row = New-Object System.Collections.Generic.List[object]
  $row.Add(@(('  ' + $script:G.v + ' '),'accent'))
  $row.Add(@(('{0,-10}' -f $label),'muted'))
  $avail = $w - 4 - 10
  $used = 0
  foreach($s in $segs){
    $t = [string]$s[0]
    if ($used -ge $avail) { break }
    if ($used + $t.Length -gt $avail) { $t = Clip $t ($avail - $used) }
    $row.Add(@($t, $s[1]))
    $used += $t.Length
  }
  $pad = $avail - $used; if($pad -lt 0){ $pad = 0 }
  $row.Add(@((' ' * $pad),'muted'))
  $row.Add(@($script:G.v,'accent'))
  return ,$row
}
# Both take a flat text,token,text,token,... list. PowerShell silently unrolls
# nested arrays, so passing pairs as arrays-of-arrays turns a single-pair call
# into two loose strings and the token gets printed as text.
function One([string]$t,$tok){
  $l = New-Object System.Collections.Generic.List[object]
  $l.Add(@($t,$tok))
  return ,$l
}
function Dotted([object[]]$flat){
  $out = New-Object System.Collections.Generic.List[object]
  for($i=0; $i -lt $flat.Count; $i+=2){
    if($i -gt 0){ $out.Add(@(('  ' + $script:G.dot + '  '),'muted')) }
    $out.Add(@([string]$flat[$i], $flat[$i+1]))
  }
  return ,$out
}

# Bright head travelling a dim rule. Driven by how far through the sampling
# interval we are, so it doubles as a countdown rather than just decoration.
function Pulse([int]$width,[double]$prog){
  $out = New-Object System.Collections.Generic.List[object]
  $pos = [int][math]::Round($prog * ($width - 1))
  if ($script:Fancy) {
    $cur = ''; $curTok = $null
    for($i=0; $i -lt $width; $i++){
      $d = $pos - $i
      $ch = $script:G.barDim; $tok = 'accentDim'
      if ($d -eq 0) { $ch = $script:G.bar; $tok = @(200,216,250) }
      elseif ($d -eq 1) { $ch = $script:G.bar; $tok = 'accentHi' }
      elseif ($d -eq 2 -or $d -eq 3) { $ch = $script:G.bar; $tok = 'accent' }
      elseif ($d -gt 3) { $ch = $script:G.bar; $tok = 'accentDim' }
      if ($null -ne $curTok -and (($tok -is [array]) -ne ($curTok -is [array]) -or ("$tok" -ne "$curTok"))) {
        $out.Add(@($cur,$curTok)); $cur = ''
      }
      $cur += $ch; $curTok = $tok
    }
    if ($cur) { $out.Add(@($cur,$curTok)) }
  } else {
    $out.Add(@(($script:G.bar * [math]::Max(1,$pos)),'accent'))
    $out.Add(@(($script:G.barDim * [math]::Max(0,$width - $pos)),'accentDim'))
  }
  return ,$out
}

function Hist-Segs([string]$h){
  $out = New-Object System.Collections.Generic.List[object]
  if(-not $h){ $out.Add(@('-','muted')); return ,$out }
  $cur=''; $curTok=''
  foreach($ch in $h.ToCharArray()){
    $tok = 'muted'
    if($ch -eq '.'){ $tok='ok' } elseif($ch -eq '!'){ $tok='warn' } elseif($ch -eq 'x'){ $tok='bad' }
    if($tok -ne $curTok -and $cur){ $out.Add(@($cur,$curTok)); $cur='' }
    $cur += $ch; $curTok = $tok
  }
  if($cur){ $out.Add(@($cur,$curTok)) }
  return ,$out
}

# --- frame ---------------------------------------------------------------
$script:dashDrawn = $false
$script:lastRows = 0
$script:lastD = $null

function Draw-Dash($d, [double]$prog = 0.0){
  $script:lastD = $d
  $w = DashW
  if (-not $script:dashDrawn) {
    try { Clear-Host } catch {}
    # A caret hopping around the panel every frame reads as flicker in its own
    # right. Restored in the wrap-up.
    if ($script:Fancy) { try { [Console]::Write($E + '[?25l') } catch {} }
    $script:dashDrawn = $true
  }

  $rows = New-Object System.Collections.Generic.List[object]
  $blank = New-Object System.Collections.Generic.List[object]; $blank.Add(@(' ','muted'))

  $rows.Add($blank)
  foreach($r in (Banner-Rows $d.hostName)){ $rows.Add($r) }
  $rows.Add($blank)

  $stTok = 'ok'
  if ($d.state -eq 'DOWN') { $stTok = 'bad' } elseif ($d.state -ne 'ok') { $stTok = 'warn' }
  $sigTok = 'ok'
  if ($null -ne $d.sigVal) { if ($d.sigVal -lt 40) { $sigTok='bad' } elseif ($d.sigVal -lt 60) { $sigTok='warn' } }

  $rows.Add((P-Top ($d.hostName + '  monitor') $w))
  $rows.Add((P-Row 'run' (Dotted @(
      ('every ' + $d.interval + 's'), 'dim',
      ('up ' + $d.elapsed), 'dim',
      ([string]$d.n + ' samples'), 'dim'
    )) $w))
  $rows.Add((P-Rule $w))

  $rows.Add((P-Row 'status' (One $d.state $stTok) $w))
  $rows.Add((P-Row 'now' (Dotted @(
      ('ping ' + $d.ping), 'fg',
      ('loss ' + $d.loss), $(if($d.lossVal -gt 0){'warn'}else{'dim'}),
      ('jitter ' + $d.jit), $(if($d.jitVal -ge 30){'warn'}else{'dim'}),
      ('dns ' + $d.dns), $(if($d.dns -eq 'FAIL'){'bad'}else{'dim'})
    )) $w))
  $rows.Add((P-Rule $w))

  if($d.wifi){
    $rows.Add((P-Row 'link' (Dotted @(
        $d.ssid, 'fg',
        $d.band, 'dim',
        $d.sig,  $sigTok,
        $d.rate, 'dim'
      )) $w))
    $rows.Add((P-Row 'ap' (One $d.ap 'dim') $w))
  } else {
    $rows.Add((P-Row 'link' (One $d.link 'fg') $w))
    $rows.Add((P-Row 'ap' (One '-' 'muted') $w))
  }
  if($d.sites -and $d.sites -ne '-'){
    $rows.Add((P-Row 'sites' (One $d.sites 'dim') $w))
  }
  $rows.Add((P-Rule $w))

  $rows.Add((P-Row 'session' (Dotted @(
      ($d.outages + ' out'),        $(if($d.outagesN -gt 0){'warn'}else{'dim'}),
      ($d.jitN + ' jit'),           $(if([int]$d.jitN -gt 0){'warn'}else{'dim'}),
      ($d.lossN + ' loss'),         $(if([int]$d.lossN -gt 0){'warn'}else{'dim'}),
      ([string]$d.roams + ' roams'),$(if([int]$d.roams -gt 0){'warn'}else{'dim'}),
      ([string]$d.aps + ' aps'),    'dim',
      ($d.dnsN + ' dns'),           $(if([int]$d.dnsN -gt 0){'warn'}else{'dim'})
    )) $w))
  $histW = [math]::Max(20, $w - 18)
  $rows.Add((P-Row 'history' (Hist-Segs ($d.hist.Substring([math]::Max(0,$d.hist.Length - $histW)))) $w))
  $rows.Add((P-Rule $w))

  $pulseW = [math]::Max(12, [math]::Min(30, $w - 34))
  $pseg = New-Object System.Collections.Generic.List[object]
  foreach($s in (Pulse $pulseW $prog)){ $pseg.Add($s) }
  $left = [math]::Max(0, [int][math]::Ceiling($d.interval * (1.0 - $prog)))
  $pseg.Add(@(('   next sample in ' + $left + 's'),'muted'))
  $rows.Add((P-Row 'pulse' $pseg $w))
  $rows.Add((P-Rule $w))

  $evs = @($d.events)
  for($i=0;$i -lt 3;$i++){
    $lbl = $(if($i -eq 0){'events'}else{''})
    if($evs.Count -eq 0 -and $i -eq 0) { $rows.Add((P-Row $lbl (One 'nothing yet' 'muted') $w)) }
    elseif($i -lt $evs.Count) { $rows.Add((P-Row $lbl (One ([string]$evs[$i]) 'warn') $w)) }
    else { $rows.Add((P-Row $lbl (One ' ' 'muted') $w)) }
  }
  $rows.Add((P-Rule $w))
  $rows.Add((P-Row 'log' (One $d.logPath 'muted') $w))
  $rows.Add((P-Bot $w))

  $rows.Add($blank)
  $qr = New-Object System.Collections.Generic.List[object]
  $qr.Add(@('  [Q] ','accentHi')); $qr.Add(@('stop and build the report','muted'))
  $rows.Add($qr)

  for($i=0; $i -lt $rows.Count; $i++){ Emit-Row $rows[$i] $w $i }
  if($script:lastRows -gt $rows.Count){
    for($i=$rows.Count; $i -lt $script:lastRows; $i++){ Emit-Row $blank $w $i }
  }
  $script:lastRows = $rows.Count
  # Park the cursor below the panel rather than leaving it mid-frame, so a
  # stray keystroke or a Ctrl+C message does not land inside the drawing.
  try { [Console]::SetCursorPosition(0, [math]::Min($rows.Count, [Console]::WindowHeight - 1)) } catch {}
}

# Called from the wait loop between samples: same frame, one tick further on,
# so the sweep and the pulse keep moving while nothing is being measured.
function Step-Dash([double]$prog){
  if ($null -eq $script:lastD) { return }
  $script:frame++
  Draw-Dash $script:lastD $prog
}
# --- end dashboard rendering ---

Write-Host ''
Write-Host ("nwa monitor - every {0}s ({1} pings/target) - {2}" -f $IntervalSec, $PingCount, $stopMsg) -ForegroundColor Green
if ($httpTargets.Count) { Write-Host ('Sites: ' + ($httpTargets -join ', ')) -ForegroundColor Green }
Write-Host ('Logging to: ' + $out) -ForegroundColor Green
Start-Sleep -Milliseconds 800

while (-not $stopReq -and ($DurationHours -le 0 -or (Get-Date) -lt $end)) {
  $tickStart = Get-Date
  $tick = [ordered]@{ t = $tickStart.ToString('o') }

  # connectivity: gateway (local hop) + internet IPs, each a burst of pings
  $q = [ordered]@{}
  if ($gateway) { $r = Test-PingSet $gateway $PingCount 1000; $q['gw'] = $r; $tick.gw = $(if ($r.recv) { $r.avg } else { -1 }) } else { $tick.gw = $null }
  foreach ($tg in $targets) { $r = Test-PingSet $tg $PingCount 1000; $q[$tg] = $r; $tick[$tg] = $(if ($r.recv) { $r.avg } else { -1 }) }
  $tick.q = $q

  # DNS resolution time (-DnsOnly: force a real query, not the local cache)
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  if ($script:hasResolve) { $rr = Resolve-DnsName -Name $dnsHost -Type A -DnsOnly -ErrorAction SilentlyContinue }
  else { $rr = $null; try { $rr = [System.Net.Dns]::GetHostAddresses($dnsHost) } catch {} }
  $sw.Stop()
  $tick.dns = $(if ($rr) { [int]$sw.Elapsed.TotalMilliseconds } else { -1 })

  # Wi-Fi link detail
  $w = Get-WlanInfo
  $tick.ssid=$w.ssid; $tick.sig=$w.sig; $tick.bssid=$w.bssid; $tick.band=$w.band; $tick.chan=$w.chan; $tick.rx=$w.rx; $tick.tx=$w.tx; $tick.radio=$w.radio

  # periodic channel-congestion scan
  if ($nbrEvery -gt 0 -and $w.chan -and ($k % $nbrEvery -eq 0)) { $tick.nbr = Get-Congestion $w.chan }
  $k++

  # adapters up + wired link speed ($null = could not enumerate; do not read that as "down")
  $allAd = @(Get-NetAdapter -ErrorAction SilentlyContinue)
  $ups = @($allAd | Where-Object { $_.Status -eq 'Up' })
  $tick.up = $(if ($allAd.Count -eq 0) { $null } else { [bool]$ups.Count })
  $eth = Get-EthMbps $ups $(if ($activeRoute) { $activeRoute.ifIndex } else { $null })
  if ($eth -ne $null) { $tick.eth = $eth }

  # Windows Wi-Fi events since last tick (disconnect reasons etc.)
  $wev = @(Get-WlanEvents $stLastEvT)
  $stLastEvT = $tickStart
  if ($wev.Count) { $tick.wlanEv = @($wev) }

  # sites (@() keeps a single result an array through ConvertTo-Json)
  # Only run site checks every $SiteCheckSec. On other ticks the key is omitted
  # entirely, so the report can tell "not checked" from "checked and failed".
  if ($httpTargets.Count) {
    $sinceSite = ((Get-Date) - $script:lastSiteCheck).TotalSeconds
    if ($script:lastSiteCheck -eq [datetime]::MinValue -or $sinceSite -ge $SiteCheckSec) {
      $tick.http = @(Test-Sites $httpTargets)
      $script:lastSiteCheck = Get-Date
    }
  } else { $tick.http = @() }

  # A full outage needs more evidence than ICMP alone: some networks block ping
  # while normal traffic keeps working. Only downgrade a ping failure when
  # something else actually crossed the internet in the same tick - an off-LAN
  # DNS answer, or a watched site responding. An on-prem resolver answering
  # proves nothing (it is reachable over the LAN during an internet outage).
  $reach = @($targets | ForEach-Object { $tick[$_] } | Where-Object { $_ -ge 0 }).Count
  $dnsProof  = $dnsIsPublic -and ($tick.dns -ge 0)
  $siteProof = [bool](@($tick.http | Where-Object { $_.ms -ge 0 }).Count)
  $isDown = ($tick.up -eq $false) -or (($reach -eq 0) -and -not $dnsProof -and -not $siteProof)
  $icmpOnly = ($reach -eq 0) -and -not $isDown
  $tick.down = [bool]$isDown
  $tick.icmpOnly = [bool]$icmpOnly
  if ($isDown -and -not $stWasDown -and ((Get-Date) - $stLastTrace).TotalSeconds -gt 300) {
    $tick.trace = @(Invoke-QuickTrace '1.1.1.1' 6)
    $stLastTrace = Get-Date
  }

  $tickEnd = Get-Date
  $tick.tEnd = $tickEnd.ToString('o')
  $tick.elapsedMs = [int][math]::Round(($tickEnd - $tickStart).TotalMilliseconds)
  $tickJson = $tick | ConvertTo-Json -Compress -Depth 6
  $script:logLines.Add($tickJson)
  Add-Content -Path $out -Value $tickJson -Encoding utf8

  # ---------- session stats + status ----------
  $i1 = $q['1.1.1.1']
  $loss = if ($i1) { $i1.loss } else { 100 }
  $jit  = if ($i1 -and $i1.jit -ne $null) { $i1.jit } else { 0 }
  if ($isDown) {
    if (-not $stWasDown) { $stOutages++; Add-Ev ($tickStart.ToString('HH:mm:ss') + ' DOWN') }
    $stDownSec += $IntervalSec
  } elseif ($stWasDown) { Add-Ev ($tickStart.ToString('HH:mm:ss') + ' back up') }
  $stWasDown = $isDown
  if (-not $isDown -and -not $icmpOnly -and $loss -gt 0) { $stLoss++ }
  if (-not $isDown -and $jit -ge 30) { $stJit++ }
  if ($tick.dns -lt 0) { $stDnsFail++; if (-not $isDown) { Add-Ev ($tickStart.ToString('HH:mm:ss') + ' DNS failed') } }
  if ($w.bssid) {
    if ($script:prevBssid -and $w.bssid -ne $script:prevBssid) { $stRoams++; Add-Ev ($tickStart.ToString('HH:mm:ss') + ' roamed to ' + $w.bssid) }
    [void]$stAps.Add($w.bssid)
    $script:prevBssid = $w.bssid
  }
  foreach ($e in $wev) { if ($e.id -eq 8003) { Add-Ev (([datetime]$e.t).ToString('HH:mm:ss') + ' ' + $e.msg) } }

  $state = if ($isDown) { 'DOWN' } elseif ($icmpOnly) { 'ICMP?' } elseif ($tick.dns -lt 0) { 'DNS!' } elseif ($loss -gt 0) { 'LOSS' } elseif ($jit -ge 30) { 'JIT' } else { 'ok' }
  $c = '.'; if ($state -eq 'DOWN') { $c = 'x' } elseif ($state -ne 'ok') { $c = '!' }
  $stHist += $c; if ($stHist.Length -gt 400) { $stHist = $stHist.Substring($stHist.Length - 400) }

  if ($interactive) {
    $sitesStr = '-'
    if ($tick.http.Count) { $sitesStr = (@($tick.http | ForEach-Object { $h=[System.Uri]$_.u; $h.Host + ' ' + $(if ($_.ms -lt 0) { 'DOWN' } else { [string]$_.ms + 'ms' }) }) -join '   ') }
    Draw-Dash @{
      hostName = $env:COMPUTERNAME
      interval = $IntervalSec
      elapsed = Format-Elapsed ((Get-Date) - $startT)
      n = $k
      state = $state
      ping = $(if ($tick.'1.1.1.1' -ge 0) { [string]$tick.'1.1.1.1' + ' ms' } else { '--' })
      loss = ([string]$loss + '%'); lossVal = $loss
      jit  = ([string]$jit + ' ms'); jitVal = $jit
      dns  = $(if ($tick.dns -ge 0) { [string]$tick.dns + ' ms' } else { 'FAIL' })
      gw   = $(if ($gateway) { $(if ($tick.gw -ge 0) { [string]$tick.gw + ' ms' } else { 'DOWN' }) } else { 'n/a' })
      wifi = ($w.sig -ne $null)
      ssid = $(if ($w.ssid) { $w.ssid } else { '-' })
      sig  = $(if ($w.sig -ne $null) { [string]$w.sig + '%' } else { '-' }); sigVal = $w.sig
      band = $(if ($w.band) { $w.band + '  ch' + $w.chan } else { '-' })
      rate = $(if ($w.rx -ne $null) { [string]$w.rx + ' Mbps' } else { '-' })
      link = $(if ($eth -ne $null) { 'wired  ' + $eth + ' Mbps' } else { 'no link' })
      ap   = $(if ($w.bssid) { $w.bssid } elseif ($bssidHidden) { 'hidden (Location off)' } else { '-' })
      roams = $stRoams; aps = $stAps.Count
      sites = $sitesStr
      hist = $stHist
      outages = [string]$stOutages; outagesN = $stOutages; downDur = ([string]$stDownSec + 's')
      lossN = [string]$stLoss; jitN = [string]$stJit; dnsN = [string]$stDnsFail
      events = @($stEvents)
      logPath = $out
    }
  } else {
    Write-Host ("[{0}] {1}  net={2}ms loss={3}% jit={4}ms  dns={5}ms  sig={6}% {7}" -f `
      $tickStart.ToString('HH:mm:ss'), $state.PadRight(4), $tick.'1.1.1.1', $loss, $jit, $tick.dns, $w.sig, $(if($w.band){$w.band}else{''}))
  }

  # wait for next tick, polling for Q. Redrawing here is what keeps the sweep
  # and the pulse moving - without it the panel would sit frozen for the whole
  # interval and read as hung.
  $deadline = $tickStart.AddSeconds($IntervalSec)
  while ((Get-Date) -lt $deadline) {
    if ($interactive) {
      try {
        if ([Console]::KeyAvailable) {
          $key = [Console]::ReadKey($true)
          if ($key.Key -eq 'Q') { $stopReq = $true; break }
        }
      } catch {}
      $elapsedTick = ((Get-Date) - $tickStart).TotalSeconds
      $prog = 0.0
      if ($IntervalSec -gt 0) { $prog = [math]::Min(1.0, [math]::Max(0.0, $elapsedTick / $IntervalSec)) }
      try { Step-Dash $prog } catch {}
    }
    Start-Sleep -Milliseconds 70
  }
}

# ---------- wrap up ----------
if ($script:Fancy -and $script:dashDrawn) { try { [Console]::Write([char]27 + '[?25h') } catch {} }
Write-Host ''
Write-Host ('Stopped. ' + $k + ' samples over ' + (Format-Elapsed ((Get-Date) - $startT)) + '.') -ForegroundColor Green
Write-Host ('Log: ' + $out) -ForegroundColor Green

New-NwaReport @($script:logLines) $interactive $script:runId | Out-Null
