# ============================================================
#  nwa - network diagnostics for Windows
#
#  Run it, watch the live status, press Q to stop - it builds
#  and opens an HTML report. The raw log (network-monitor.jsonl)
#  is written continuously, so nothing is lost on a crash.
#  Nothing is uploaded by this script; analysis is local.
#
#  Usage:
#    powershell -ep bypass -f .\nwa.ps1                    monitor until Q
#    powershell -ep bypass -f .\nwa.ps1 -Snapshot          one-shot check
#    powershell -ep bypass -f .\nwa.ps1 -Sites "a.com"     also test your sites
#
#  This file is generated by build.ps1 from src/nwa.src.ps1
#  plus index.html (the embedded report template). Edit src/,
#  then run build.ps1.
# ============================================================
param(
  [switch]$Snapshot,                 # one-shot health check instead of monitoring
  [string[]]$Sites = @(),            # extra sites to test, e.g. -Sites "yourapp.com","intranet.local"
  [int]$IntervalSec = 10,            # seconds between checks
  [double]$DurationHours = 0,        # 0 = run until Q / Ctrl+C
  [int]$PingCount = 5,               # pings per target per check (loss / jitter)
  [int]$NeighborScanSec = 300,       # how often to scan nearby APs (0 = never)
  [string]$OutDir = '',              # where files go (default: Desktop)
  [switch]$Report,                   # always generate the report at the end (no prompt)
  [string]$RunLabel = '',            # e.g. baseline, post-AP-change, validation
  [switch]$IncludePublicIp            # snapshot only; makes a request to api.ipify.org
)

$ErrorActionPreference = 'SilentlyContinue'
$ProgressPreference    = 'SilentlyContinue'
$script:ToolVersion    = '0.1.0'

# make sure the Windows networking modules (NetAdapter, DnsClient) are findable
$winMods = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\Modules'
if ((Test-Path $winMods) -and ($env:PSModulePath -notlike ('*' + $winMods + '*'))) { $env:PSModulePath += ';' + $winMods }
$script:hasResolve = [bool](Get-Command Resolve-DnsName -ErrorAction SilentlyContinue)

# Embedded report template: base64 of index.html from this repo (see build.ps1).
# It is only ever written to an .html file - never executed as code.
$NWA_B64 = '@@NWA_TEMPLATE_B64@@'

# Where files go. The LOG is appended every few seconds, so it must NOT live in a
# OneDrive/Dropbox-synced folder (sync engines lock and fork rapidly-changing files
# - that is exactly what produced empty reports from a synced Desktop). The report
# is a single write at the end, so the Desktop is fine for it.
if ($OutDir) { $LogDir = $OutDir; $ReportDir = $OutDir }
else {
  $LogDir = Join-Path $env:LOCALAPPDATA 'nwa'
  $ReportDir = [Environment]::GetFolderPath('Desktop')
}
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
# Every capture gets its own stable ID. This preserves evidence for before/after
# comparisons instead of overwriting the previous monitor log and report.
$script:runId = (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ') + '-' + ([guid]::NewGuid().ToString('N').Substring(0,6))
# every line written to the log is also kept in memory; the report is built from
# memory so a sync engine mangling the log file cannot produce an empty report
$script:logLines = New-Object System.Collections.Generic.List[string]

$targets = @('1.1.1.1','8.8.8.8')
$dnsHost = 'google.com'
$httpTargets = @(foreach ($s in $Sites) { $s = $s.Trim(); if ($s) { if ($s -match '^https?://') { $s } else { 'https://' + $s } } })

# ---------- helpers ----------

# fast multi-ping (no 1s gap) - returns recv/loss/min/avg/max/jitter
function Test-PingSet([string]$ip,[int]$count,[int]$timeoutMs){
  $rtts = New-Object System.Collections.Generic.List[int]
  $pinger = New-Object System.Net.NetworkInformation.Ping
  for ($i=0; $i -lt $count; $i++) {
    try { $pr = $pinger.Send($ip,$timeoutMs); if ($pr.Status -eq 'Success') { $rtts.Add([int]$pr.RoundtripTime) } } catch {}
  }
  $recv = $rtts.Count
  $o = [ordered]@{ recv=$recv; loss=[math]::Round((1-($recv/$count))*100,0); min=$null; avg=$null; max=$null; jit=$null }
  if ($recv -gt 0) {
    $o.min = ($rtts | Measure-Object -Minimum).Minimum
    $o.max = ($rtts | Measure-Object -Maximum).Maximum
    $o.avg = [math]::Round(($rtts | Measure-Object -Average).Average,0)
    if ($rtts.Count -gt 1) {
      $d = New-Object System.Collections.Generic.List[int]
      for ($i=1; $i -lt $rtts.Count; $i++) { $d.Add([math]::Abs($rtts[$i]-$rtts[$i-1])) }
      $o.jit = [math]::Round(($d | Measure-Object -Average).Average,0)
    } else { $o.jit = 0 }
  }
  return $o
}

# current Wi-Fi association (ssid, bssid, signal, band, channel, rates)
function Get-WlanInfo {
  $w = [ordered]@{ ssid=$null; sig=$null; bssid=$null; band=$null; chan=$null; rx=$null; tx=$null; radio=$null }
  foreach ($l in (netsh wlan show interfaces)) {
    if     ($l -match '^\s*SSID\s+:\s*(.+)$')                    { $w.ssid=$matches[1].Trim() }
    elseif ($l -match '^\s*Signal\s*:\s*(\d+)%')                 { $w.sig=[int]$matches[1] }
    elseif ($l -match 'BSSID\s*:\s*([0-9a-fA-F:]{17})')          { $w.bssid=$matches[1].Trim() }
    elseif ($l -match '^\s*Band\s*:\s*(.+)$')                    { $w.band=$matches[1].Trim() }
    elseif ($l -match '^\s*Channel\s*:\s*(\d+)')                 { $w.chan=[int]$matches[1] }
    elseif ($l -match '^\s*Receive rate \(Mbps\)\s*:\s*([\d\.]+)'){ $w.rx=[double]$matches[1] }
    elseif ($l -match '^\s*Transmit rate \(Mbps\)\s*:\s*([\d\.]+)'){ $w.tx=[double]$matches[1] }
    elseif ($l -match '^\s*Radio type\s*:\s*(.+)$')              { $w.radio=$matches[1].Trim() }
  }
  return $w
}

# scan nearby Wi-Fi networks -> how crowded is my channel
function Get-Congestion([int]$myChan){
  $chans = New-Object System.Collections.Generic.List[int]
  foreach ($l in (netsh wlan show networks mode=bssid)) {
    if ($l -match '^\s*Channel\s*:\s*(\d+)') { $chans.Add([int]$matches[1]) }
  }
  [ordered]@{ total = $chans.Count; coChan = @($chans | Where-Object { $_ -eq $myChan }).Count; chan = $myChan }
}

# new Windows Wi-Fi events since last check (connect / fail / disconnect + reason)
$script:wlanLogOk = $true
$script:wlanSeen  = New-Object System.Collections.Generic.HashSet[long]
function Get-WlanEvents([datetime]$since){
  if (-not $script:wlanLogOk) { return @() }
  $out = @()
  try {
    $evs = Get-WinEvent -FilterHashtable @{
      LogName='Microsoft-Windows-WLAN-AutoConfig/Operational'
      Id=@(8001,8002,8003)
      StartTime=$since.AddSeconds(-5)
    } -ErrorAction Stop
    foreach ($e in $evs) {
      if (-not $script:wlanSeen.Add([long]$e.RecordId)) { continue }
      $msg = ''
      if ($e.Id -eq 8003) {
        $msg = 'disconnect'
        if ($e.Message -match 'Reason:\s*(.+)') { $msg = 'disconnect: ' + $matches[1].Trim() }
      } elseif ($e.Id -eq 8001) { $msg = 'connected' }
      elseif ($e.Id -eq 8002)   { $msg = 'connection failed' }
      $out += [ordered]@{ t=$e.TimeCreated.ToString('o'); id=$e.Id; msg=$msg }
    }
    if ($script:wlanSeen.Count -gt 500) { $script:wlanSeen.Clear() }
  } catch {
    if ($_.FullyQualifiedErrorId -notmatch 'NoMatchingEvents') { $script:wlanLogOk = $false }
  }
  return @($out | Sort-Object t)
}

# short TTL-stepped trace: where does the path die? (bounded, ~4s worst case)
function Invoke-QuickTrace([string]$dest,[int]$maxHops){
  $hops = @()
  $p = New-Object System.Net.NetworkInformation.Ping
  $buf = New-Object byte[] 8
  for ($ttl=1; $ttl -le $maxHops; $ttl++) {
    try {
      $opt = New-Object System.Net.NetworkInformation.PingOptions($ttl,$true)
      $r = $p.Send($dest,700,$buf,$opt)
      if ($r.Status -eq 'Success')        { $hops += $r.Address.ToString(); break }
      elseif ($r.Status -eq 'TtlExpired') { $hops += $r.Address.ToString() }
      else                                { $hops += '*' }
    } catch { $hops += '*' }
  }
  return $hops
}

# wired adapter link speed in Mbps (catches 1000 -> 100 renegotiation)
function Get-EthMbps($upAdapters){
  $e = $upAdapters | Where-Object { $_.PhysicalMediaType -notmatch '802.11|Wireless' } | Select-Object -First 1
  if (-not $e) { return $null }
  if ($e.LinkSpeed -match '([\d\.]+)\s*(G|M)bps') {
    $v = [double]$matches[1]; if ($matches[2] -eq 'G') { $v = $v * 1000 }
    return [int]$v
  }
  return $null
}

# HTTP(S) reachability. ms = -1 means could not reach at all; any status code counts as reached.
function Test-Sites([string[]]$urls){
  @(foreach ($u in $urls) {
    $hsw = [System.Diagnostics.Stopwatch]::StartNew()
    try {
      $resp = Invoke-WebRequest -Uri $u -Method Head -TimeoutSec 6 -UseBasicParsing -ErrorAction Stop
      $hsw.Stop()
      [ordered]@{ u = $u; ms = [int]$hsw.Elapsed.TotalMilliseconds; code = [int]$resp.StatusCode }
    } catch {
      $hsw.Stop()
      $code = 0
      if ($_.Exception.Response) { try { $code = [int]$_.Exception.Response.StatusCode } catch {} }
      if ($code -gt 0) { [ordered]@{ u = $u; ms = [int]$hsw.Elapsed.TotalMilliseconds; code = $code } }
      else             { [ordered]@{ u = $u; ms = -1; code = 0 } }
    }
  })
}

# build network-report.html from the in-memory data lines (never re-reads the log file)
function New-NwaReport([string[]]$jsonLines,[bool]$OpenIt,[string]$runId){
  if ($NWA_B64 -like '@@*') { Write-Host 'No report template embedded (source build) - run build.ps1 first.' -ForegroundColor DarkYellow; return $null }
  if (-not $jsonLines -or $jsonLines.Count -eq 0) { Write-Host 'No data captured - report skipped.' -ForegroundColor DarkYellow; return $null }
  try {
    $tpl = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($NWA_B64))
    $arr = '[' + ($jsonLines -join ',') + ']'
    $arr = $arr.Replace('</','<\/')   # keep '</script>' inside logged strings from breaking the page
    $html = $tpl.Replace('window.NWA_EMBEDDED = window.NWA_EMBEDDED || null;', 'window.NWA_EMBEDDED = ' + $arr + ';')
    $rp = Join-Path $ReportDir ('network-report-' + $runId + '.html')
    Set-Content -Path $rp -Value $html -Encoding utf8
    Write-Host ('Report: ' + $rp) -ForegroundColor Green
    if ($OpenIt) { Start-Process $rp }
    return $rp
  } catch { Write-Host ('Could not build report: ' + $_) -ForegroundColor Red; return $null }
}

# ---------- environment context (collected once) ----------

$activeRoute = $null
$gateway = $null
try {
  # Prefer the actual lowest-metric IPv4 default route over an arbitrary
  # "first" adapter. This matters when Wi-Fi, Ethernet, and a VPN coexist.
  $r = Get-NetRoute -DestinationPrefix '0.0.0.0/0' -ErrorAction Stop |
    Where-Object { $_.NextHop -and $_.NextHop -ne '0.0.0.0' } |
    Sort-Object @{ Expression = { [int]$_.RouteMetric + [int]$_.InterfaceMetric } }, RouteMetric |
    Select-Object -First 1
  if ($r) {
    $gateway = [string]$r.NextHop
    $routeAdapter = Get-NetAdapter -InterfaceIndex $r.InterfaceIndex -ErrorAction SilentlyContinue
    $activeRoute = [ordered]@{
      ifIndex = [int]$r.InterfaceIndex
      alias = if ($routeAdapter) { [string]$routeAdapter.Name } else { $null }
      nextHop = $gateway
      metric = [int]$r.RouteMetric + [int]$r.InterfaceMetric
    }
  }
} catch {}
if (-not $gateway) {
  try { $gateway = (Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway } | Select-Object -First 1).IPv4DefaultGateway.NextHop } catch {}
}

$upIdx = @((Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }).ifIndex)
$dnsIdx = if ($activeRoute) { @($activeRoute.ifIndex) } else { $upIdx }
$dnsServers = @(Get-DnsClientServerAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
  Where-Object { $_.ServerAddresses -and ($dnsIdx -contains $_.InterfaceIndex) } |
  ForEach-Object { $_.ServerAddresses } | Select-Object -Unique)

# A DNS answer only proves the internet is reachable when the resolver is off-LAN.
# On a domain-joined PC the resolver is usually an on-prem DC, which keeps answering
# from the LAN during an internet outage - so it cannot be used as proof of uptime.
function Test-OffLanAddress([string]$ip){
  if (-not $ip) { return $false }
  if ($ip -notmatch '^\d{1,3}(\.\d{1,3}){3}$') { return $false }
  $o = $ip.Split('.') | ForEach-Object { [int]$_ }
  if ($o[0] -eq 10) { return $false }
  if ($o[0] -eq 127) { return $false }
  if ($o[0] -eq 172 -and $o[1] -ge 16 -and $o[1] -le 31) { return $false }
  if ($o[0] -eq 192 -and $o[1] -eq 168) { return $false }
  if ($o[0] -eq 169 -and $o[1] -eq 254) { return $false }
  if ($o[0] -eq 100 -and $o[1] -ge 64 -and $o[1] -le 127) { return $false }   # CGNAT
  return $true
}
# Conservative: every configured resolver must be off-LAN, because Windows may use any of them.
$dnsIsPublic = ($dnsServers.Count -gt 0) -and -not (@($dnsServers | Where-Object { -not (Test-OffLanAddress $_) }).Count)
if (-not $dnsIsPublic) {
  Write-Host 'DNS resolver is on the local network - ICMP failures will be treated as real outages.' -ForegroundColor DarkYellow
}
if ($gateway) {
  $gwTest = Test-PingSet $gateway 2 800
  if ($gwTest.recv -eq 0) { Write-Host "Gateway $gateway doesn't answer ping (ICMP blocked) - skipping gateway checks." -ForegroundColor DarkYellow; $gateway = $null }
}

# adapter + driver + power management (radio power saving is a common cause of drops)
$adapterInfo = $null
try {
  $a = Get-NetAdapter -ErrorAction Stop | Where-Object { $_.Status -eq 'Up' } |
       Sort-Object { if ($activeRoute -and $_.ifIndex -eq $activeRoute.ifIndex) { 0 } elseif ($_.PhysicalMediaType -match '802.11|Wireless') { 1 } else { 2 } } |
       Select-Object -First 1
  if ($a) {
    $pm = $null
    try { $p = Get-NetAdapterPowerManagement -Name $a.Name -ErrorAction Stop
          if ($p) { $pm = [ordered]@{ selectiveSuspend = [string]$p.SelectiveSuspend; sleepOnDisconnect = [string]$p.DeviceSleepOnDisconnect } } } catch {}
    $adapterInfo = [ordered]@{
      name = $a.Name; description = $a.InterfaceDescription
      driverVersion = [string]$a.DriverVersion; driverDate = [string]$a.DriverDate
      linkSpeed = [string]$a.LinkSpeed; powerMgmt = $pm
    }
  }
} catch {}

# IPv6 reachability (context)
$ipv6 = $null
try { $r6 = Test-PingSet '2606:4700:4700::1111' 2 1200; $ipv6 = [ordered]@{ reachable = ($r6.recv -gt 0); ms = $r6.avg } }
catch { $ipv6 = [ordered]@{ reachable = $false; ms = $null } }

# Windows 11 24H2 hides BSSID / neighbor networks when Location is off
$w0 = Get-WlanInfo
$bssidHidden = $false
if ($w0.sig -ne $null -and -not $w0.bssid) {
  $bssidHidden = $true
  Write-Host 'Windows is hiding the AP identity (Location is off?) - roam detection will be limited.' -ForegroundColor DarkYellow
  Write-Host 'Enable Settings > Privacy & security > Location to get full Wi-Fi detail.' -ForegroundColor DarkYellow
}

# ============================================================
#  SNAPSHOT MODE
# ============================================================
if ($Snapshot) {
  $snapData = [ordered]@{}
  $snapData.schema      = 'nwa-report/1'
  $snapData.toolVersion = $script:ToolVersion
  $snapData.runId       = $script:runId
  $snapData.runLabel    = $RunLabel
  $snapData.generatedAt = (Get-Date).ToString('o')
  $snapData.hoursWindow = 24

  Write-Host 'Collecting system info...'
  $os = Get-CimInstance Win32_OperatingSystem
  $snapData.system = [ordered]@{
    computerName = $env:COMPUTERNAME
    user         = $env:USERNAME
    os           = $os.Caption
    osVersion    = [string]$os.Version
    uptimeHours  = [math]::Round(((Get-Date) - $os.LastBootUpTime).TotalHours, 1)
  }

  Write-Host 'Collecting network adapters...'
  $snapData.adapters = @(Get-NetAdapter | ForEach-Object {
    [ordered]@{
      name        = $_.Name
      description = $_.InterfaceDescription
      status      = [string]$_.Status
      macAddress  = $_.MacAddress
      linkSpeed   = $_.LinkSpeed
      mediaType   = [string]$_.PhysicalMediaType
      ifIndex     = $_.ifIndex
    }
  })

  Write-Host 'Collecting IP configuration...'
  $snapData.ipConfig = @(Get-NetIPConfiguration | ForEach-Object {
    [ordered]@{
      alias   = $_.InterfaceAlias
      ipv4    = [string]$_.IPv4Address.IPAddress
      ipv6    = [string]$_.IPv6Address.IPAddress
      gateway = [string]$_.IPv4DefaultGateway.NextHop
    }
  })

  $snapData.dns = @(Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object { $_.ServerAddresses } | ForEach-Object {
    [ordered]@{ alias = $_.InterfaceAlias; servers = @($_.ServerAddresses) }
  })

  Write-Host 'Collecting adapter traffic counters...'
  $snapData.adapterStats = @(Get-NetAdapterStatistics | ForEach-Object {
    [ordered]@{
      name                   = $_.Name
      receivedBytes          = [int64]$_.ReceivedBytes
      sentBytes              = [int64]$_.SentBytes
      receivedUnicastPackets = [int64]$_.ReceivedUnicastPackets
      sentUnicastPackets     = [int64]$_.SentUnicastPackets
    }
  })

  Write-Host 'Collecting Wi-Fi state...'
  $snapData.wifi = [ordered]@{}
  $wifiRaw = netsh wlan show interfaces
  if ($wifiRaw) {
    $snapData.wifi.raw = ($wifiRaw -join "`n")
    foreach ($line in $wifiRaw) {
      if ($line -match '^\s*(SSID|BSSID|Signal|Channel|Band|Radio type|Receive rate \(Mbps\)|Transmit rate \(Mbps\)|Authentication|State)\s*:\s*(.+)$') {
        $snapData.wifi[$matches[1].Trim()] = $matches[2].Trim()
      }
    }
  }

  Write-Host 'Running latency tests...'
  $snapData.latency = @(foreach ($t in @('1.1.1.1','8.8.8.8','google.com')) {
    $r = Test-PingSet $t 4 1200
    [ordered]@{
      target   = $t
      sent     = 4
      received = $r.recv
      lossPct  = $r.loss
      avgMs    = $r.avg
      minMs    = $r.min
      maxMs    = $r.max
    }
  })

  Write-Host 'Testing DNS resolution speed...'
  $snapData.dnsTest = @(foreach ($h in @('google.com','cloudflare.com','microsoft.com')) {
    $sw  = [System.Diagnostics.Stopwatch]::StartNew()
    $res = Resolve-DnsName -Name $h -Type A -DnsOnly -ErrorAction SilentlyContinue
    $sw.Stop()
    [ordered]@{
      host      = $h
      ms        = [math]::Round($sw.Elapsed.TotalMilliseconds, 0)
      resolved  = [bool]$res
      addresses = @($res | Where-Object { $_.IPAddress } | ForEach-Object { $_.IPAddress })
    }
  })

  Write-Host 'Collecting active connections...'
  $procs = @{}
  Get-Process | ForEach-Object { $procs[$_.Id] = $_.ProcessName }
  $snapData.connections = @(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{
      localAddress  = $_.LocalAddress
      localPort     = $_.LocalPort
      remoteAddress = $_.RemoteAddress
      remotePort    = $_.RemotePort
      process       = $procs[[int]$_.OwningProcess]
      pid           = $_.OwningProcess
    }
  } | Select-Object -First 250)

  Write-Host 'Collecting listening ports...'
  $snapData.listening = @(Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{
      localAddress = $_.LocalAddress
      localPort    = $_.LocalPort
      process      = $procs[[int]$_.OwningProcess]
      pid          = $_.OwningProcess
    }
  } | Select-Object -First 150)

  $snapData.routes = @(Get-NetRoute -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{ ifAlias = $_.InterfaceAlias; nextHop = $_.NextHop; metric = $_.RouteMetric }
  })

  $snapData.publicIpCollected = [bool]$IncludePublicIp
  if ($IncludePublicIp) {
    Write-Host 'Looking up public IP (best effort)...'
    try   { $snapData.publicIp = (Invoke-RestMethod -Uri 'https://api.ipify.org?format=json' -TimeoutSec 5).ip }
    catch { $snapData.publicIp = $null }
  } else { $snapData.publicIp = $null }

  Write-Host 'Collecting recent network events (last 24h)...'
  $since = (Get-Date).AddHours(-24)
  $snapData.events = @(Get-WinEvent -FilterHashtable @{ LogName = 'System'; StartTime = $since } -ErrorAction SilentlyContinue |
    Where-Object { $_.ProviderName -match 'Tcpip|Dhcp|WLAN|NetworkProfile|Netwtw|NDIS|Wlansvc|Dnscache' } |
    Select-Object -First 300 | ForEach-Object {
      [ordered]@{
        time     = $_.TimeCreated.ToString('o')
        level    = [string]$_.LevelDisplayName
        provider = $_.ProviderName
        id       = $_.Id
        message  = ($_.Message -replace '\s+', ' ').Trim()
      }
    })

  $outPath = Join-Path $LogDir ('network-report-' + $script:runId + '.json')
  $snapData | ConvertTo-Json -Depth 8 | Out-File -FilePath $outPath -Encoding utf8
  Write-Host ('Data: ' + $outPath) -ForegroundColor Green
  $interactive = $true
  try { $interactive = ($Host.Name -eq 'ConsoleHost') -and -not [Console]::IsInputRedirected } catch { $interactive = $false }
  $compact = $snapData | ConvertTo-Json -Compress -Depth 8
  New-NwaReport @($compact) ($interactive -or $Report) $script:runId | Out-Null
  return
}

# ============================================================
#  MONITOR MODE
# ============================================================
$out = Join-Path $LogDir ('network-monitor-' + $script:runId + '.jsonl')

$meta = [ordered]@{
  schema          = 'nwa-monitor/1'
  toolVersion     = $script:ToolVersion
  runId           = $script:runId
  runLabel        = $RunLabel
  startedAt       = (Get-Date).ToString('o')
  intervalSec     = $IntervalSec
  durationHours   = $DurationHours
  pingCount       = $PingCount
  neighborScanSec = $NeighborScanSec
  computerName    = $env:COMPUTERNAME
  targets         = $targets
  gateway         = $gateway
  activeRoute     = $activeRoute
  dnsHost         = $dnsHost
  dnsServers      = $dnsServers
  dnsIsPublic     = $dnsIsPublic
  adapter         = $adapterInfo
  ipv6            = $ipv6
  bssidHidden     = $bssidHidden
  httpTargets     = $httpTargets
}
$metaJson = $meta | ConvertTo-Json -Compress
$script:logLines.Add($metaJson)
Set-Content -Path $out -Value $metaJson -Encoding utf8

$interactive = $true
try { $interactive = ($Host.Name -eq 'ConsoleHost') -and -not [Console]::IsInputRedirected } catch { $interactive = $false }

$end = (Get-Date).AddHours($DurationHours)
$stopMsg = if ($DurationHours -le 0) { 'until you press Q' } else { "until $end (or Q)" }
if (-not $interactive) { $stopMsg = if ($DurationHours -le 0) { 'until Ctrl+C' } else { "until $end" } }

# ---------- session state ----------
$nbrEvery  = if ($NeighborScanSec -gt 0) { [math]::Max(1, [int]($NeighborScanSec / $IntervalSec)) } else { 0 }
$k = 0
$stopReq = $false
$startT = Get-Date
$stLastEvT = Get-Date
$stRoams = 0; $stAps = New-Object System.Collections.Generic.HashSet[string]
$stOutages = 0; $stDownSec = 0; $stWasDown = $false
$stLoss = 0; $stJit = 0; $stDnsFail = 0
$stEvents = New-Object System.Collections.Generic.List[string]
$stHist = ''
$stLastTrace = [datetime]::MinValue
$script:dashDrawn = $false
$script:lastRows = 0

function Format-Elapsed([timespan]$ts){
  if ($ts.TotalHours -ge 1) { return ('{0}h {1:d2}m' -f [int][math]::Floor($ts.TotalHours), $ts.Minutes) }
  return ('{0:d2}:{1:d2}' -f $ts.Minutes, $ts.Seconds)
}
function Add-Ev([string]$s){ $stEvents.Add($s); while ($stEvents.Count -gt 3) { $stEvents.RemoveAt(0) } }

# --- dashboard rendering ---
$script:NwaLogo = @(
  ' _  _ __      ___   ',
  '| \| |\ \    / /_\  ',
  '| .` | \ \/\/ / _ \ ',
  '|_|\_|  \_/\_/_/ \_\'
)
$script:NwaTag = 'network analysis - github.com/SolusKossi/nwa'

# a "row" is a list of segments; a segment is @(text, consoleColor)
function New-Box([string]$title,$rows,[int]$w){
  $inner = $w - 4
  $out = New-Object System.Collections.Generic.List[object]
  $t = '+-- ' + $title + ' '
  $head = New-Object System.Collections.Generic.List[object]
  $head.Add(@($t,'Cyan'))
  $head.Add(@((('-' * [math]::Max(0,$w - $t.Length - 1)) + '+'),'DarkGray'))
  $out.Add($head)
  foreach($r in $rows){
    $line = New-Object System.Collections.Generic.List[object]
    $line.Add(@('| ','DarkGray'))
    $len = 0
    foreach($s in $r){
      $txt = [string]$s[0]
      if ($len -ge $inner) { break }
      if ($len + $txt.Length -gt $inner) { $txt = $txt.Substring(0, $inner - $len) }  # clip to box
      $line.Add(@($txt, $s[1]))
      $len += $txt.Length
    }
    $line.Add(@(((' ' * [math]::Max(0,$inner - $len)) + ' |'),'DarkGray'))
    $out.Add($line)
  }
  $foot = New-Object System.Collections.Generic.List[object]
  $foot.Add(@(('+' + ('-' * ($w-2)) + '+'),'DarkGray'))
  $out.Add($foot)
  return ,$out
}
function Join-BoxRows($left,$right,[int]$lw,[int]$gap){
  $n = [math]::Max($left.Count,$right.Count)
  $out = New-Object System.Collections.Generic.List[object]
  for($i=0;$i -lt $n;$i++){
    $row = New-Object System.Collections.Generic.List[object]
    if($i -lt $left.Count){ foreach($s in $left[$i]){ $row.Add($s) } } else { $row.Add(@((' ' * $lw),'DarkGray')) }
    $row.Add(@((' ' * $gap),'DarkGray'))
    if($i -lt $right.Count){ foreach($s in $right[$i]){ $row.Add($s) } }
    $out.Add($row)
  }
  return ,$out
}
function KV([string]$k,[string]$v,[string]$vc){
  $r = New-Object System.Collections.Generic.List[object]
  $r.Add(@($k.PadRight(9),'DarkGray')); $r.Add(@($v,$vc))
  return ,$r
}
function KV2([string]$k1,[string]$v1,[string]$c1,[string]$k2,[string]$v2,[string]$c2,[int]$half){
  $r = New-Object System.Collections.Generic.List[object]
  $r.Add(@($k1.PadRight(9),'DarkGray'))
  $r.Add(@($v1.PadRight([math]::Max($v1.Length + 2, $half - 9)),$c1))   # always at least 2 spaces before pair 2
  $r.Add(@($k2.PadRight(9),'DarkGray'))
  $r.Add(@($v2,$c2))
  return ,$r
}
function HistSegs([string]$h){
  $row = New-Object System.Collections.Generic.List[object]
  if(-not $h){ $row.Add(@('-','DarkGray')); return ,$row }
  $cur=''; $curC=''
  foreach($ch in $h.ToCharArray()){
    $c = 'DarkGray'
    if($ch -eq '.'){ $c='DarkGreen' } elseif($ch -eq '!'){ $c='Yellow' } elseif($ch -eq 'x'){ $c='Red' }
    if($c -ne $curC -and $cur){ $row.Add(@($cur,$curC)); $cur='' }
    $cur += $ch; $curC = $c
  }
  if($cur){ $row.Add(@($cur,$curC)) }
  return ,$row
}
function Write-SegRow($row,[int]$w){
  $len = 0
  foreach($s in $row){
    $c = 'Gray'; if ($s.Count -gt 1 -and $s[1]) { $c = [string]$s[1] }
    Write-Host ([string]$s[0]) -NoNewline -ForegroundColor $c
    $len += ([string]$s[0]).Length
  }
  if($len -lt $w){ Write-Host (' ' * ($w - $len)) -NoNewline }
  Write-Host ''
}

function Draw-Dash($d){
  $w = 90
  try { $w = [math]::Min(110, [math]::Max(70, [Console]::WindowWidth - 1)) } catch {}
  try {
    if (-not $script:dashDrawn) { try { Clear-Host } catch {}; $script:dashDrawn = $true }
    [Console]::SetCursorPosition(0,0)
  } catch { $script:dashDrawn = $true }

  $rows = New-Object System.Collections.Generic.List[object]

  # header: run info left, NWA logo + attribution right
  $rw = $script:NwaTag.Length
  $leftHead = @(
    '',
    (' NWA MONITOR   ' + $d.hostName),
    (' up ' + $d.elapsed + '   ' + $d.n + ' samples   every ' + $d.interval + 's'),
    ' [Q] stop and build report',
    ''
  )
  for($i=0;$i -lt 5;$i++){
    $r = New-Object System.Collections.Generic.List[object]
    $lt = $leftHead[$i]
    $r.Add(@($lt.PadRight([math]::Max(1,$w - $rw - 1)), $(if($i -eq 1){'White'}else{'DarkGray'})))
    if($i -lt 4){ $r.Add(@($script:NwaLogo[$i].PadLeft($rw),'Cyan')) }
    else        { $r.Add(@($script:NwaTag.PadLeft($rw),'DarkGray')) }
    $rows.Add($r)
  }
  $blank = New-Object System.Collections.Generic.List[object]; $blank.Add(@(' ','DarkGray')); $rows.Add($blank)

  # status colors
  $stCol = 'Green'; if ($d.state -eq 'DOWN') { $stCol = 'Red' } elseif ($d.state -ne 'ok') { $stCol = 'Yellow' }
  $sigCol = 'Green'; if ($d.sigVal -ne $null) { if ($d.sigVal -lt 40) { $sigCol='Red' } elseif ($d.sigVal -lt 60) { $sigCol='Yellow' } }
  $lossCol = $(if($d.lossVal -gt 0){'Yellow'}else{'Gray'})
  $jitCol  = $(if($d.jitVal -ge 30){'Yellow'}else{'Gray'})
  $dnsCol  = $(if($d.dns -eq 'FAIL'){'Red'}else{'Gray'})

  $twoCol = ($w -ge 86)
  $bw = $(if($twoCol){ [int](($w - 2) / 2) } else { $w })
  $half = [int](($bw - 4) / 2)

  # CONNECTION box
  $cRows = @(
    (KV2 'status' $d.state $stCol 'ping' $d.ping 'Gray' $half),
    (KV2 'loss' $d.loss $lossCol 'jitter' $d.jit $jitCol $half),
    (KV2 'dns' $d.dns $dnsCol 'gateway' $d.gw 'Gray' $half)
  )
  # LINK box
  if($d.wifi){
    $lRows = @(
      (KV2 'ssid' $d.ssid 'White' 'signal' $d.sig $sigCol $half),
      (KV2 'band' $d.band 'Gray' 'rate' $d.rate 'Gray' $half),
      (KV 'ap' $d.ap 'Gray')
    )
  } else {
    $lRows = @(
      (KV 'link' $d.link 'White'),
      (KV 'ap' '-' 'DarkGray'),
      (KV ' ' ' ' 'DarkGray')
    )
  }
  # SESSION box
  $sRows = @(
    (KV2 'outages' ($d.outages + ' (' + $d.downDur + ')') $(if($d.outagesN -gt 0){'Yellow'}else{'Gray'}) 'loss t.' $d.lossN $(if([int]$d.lossN -gt 0){'Yellow'}else{'Gray'}) $half),
    (KV2 'jit>=30' $d.jitN $(if([int]$d.jitN -gt 0){'Yellow'}else{'Gray'}) 'dns fail' $d.dnsN $(if([int]$d.dnsN -gt 0){'Yellow'}else{'Gray'}) $half),
    (KV2 'roams' ([string]$d.roams) $(if([int]$d.roams -gt 0){'Yellow'}else{'Gray'}) 'aps seen' ([string]$d.aps) 'Gray' $half)
  )
  # EVENTS box
  $eRows = New-Object System.Collections.Generic.List[object]
  if($d.events.Count -eq 0){
    $r0 = New-Object System.Collections.Generic.List[object]; $r0.Add(@('no events yet','DarkGray')); $eRows.Add($r0)
  }
  foreach($ev in $d.events){
    $re = New-Object System.Collections.Generic.List[object]; $re.Add(@([string]$ev,'Yellow')); $eRows.Add($re)
  }
  while($eRows.Count -lt 3){
    $rb = New-Object System.Collections.Generic.List[object]; $rb.Add(@(' ','DarkGray')); $eRows.Add($rb)
  }

  if($twoCol){
    foreach($r in (Join-BoxRows (New-Box 'CONNECTION' $cRows $bw) (New-Box 'LINK' $lRows $bw) $bw ($w - 2*$bw))){ $rows.Add($r) }
    foreach($r in (Join-BoxRows (New-Box 'SESSION' $sRows $bw) (New-Box 'EVENTS' $eRows $bw) $bw ($w - 2*$bw))){ $rows.Add($r) }
  } else {
    foreach($b in @((New-Box 'CONNECTION' $cRows $bw),(New-Box 'LINK' $lRows $bw),(New-Box 'SESSION' $sRows $bw),(New-Box 'EVENTS' $eRows $bw))){
      foreach($r in $b){ $rows.Add($r) }
    }
  }

  # sites + history (full width)
  if($d.sites -and $d.sites -ne '-'){
    $sRow = New-Object System.Collections.Generic.List[object]
    $sRow.Add(@(' sites    ','DarkGray')); $sRow.Add(@($d.sites,'Gray'))
    $rows.Add($sRow)
    $rows.Add($blank)
  }
  $histW = [math]::Max(20, $w - 12)
  $hRow = New-Object System.Collections.Generic.List[object]
  $hRow.Add(@(' history  [','DarkGray'))
  foreach($s in (HistSegs ($d.hist.Substring([math]::Max(0,$d.hist.Length - $histW))))){ $hRow.Add($s) }
  $hRow.Add(@(']','DarkGray'))
  $rows.Add($hRow)
  $lRow = New-Object System.Collections.Generic.List[object]
  $lRow.Add(@('           ','DarkGray')); $lRow.Add(@('.','DarkGreen')); $lRow.Add(@(' ok   ','DarkGray'))
  $lRow.Add(@('!','Yellow')); $lRow.Add(@(' degraded   ','DarkGray')); $lRow.Add(@('x','Red')); $lRow.Add(@(' down','DarkGray'))
  $rows.Add($lRow)
  $rows.Add($blank)
  $pRow = New-Object System.Collections.Generic.List[object]
  $pRow.Add(@((' log  ' + $d.logPath),'DarkGray'))
  $rows.Add($pRow)

  foreach($r in $rows){ Write-SegRow $r $w }
  # clear leftover lines from a previous, taller frame
  if($script:lastRows -gt $rows.Count){ for($i=$rows.Count;$i -lt $script:lastRows;$i++){ Write-Host (' ' * $w) } }
  $script:lastRows = $rows.Count
}
# --- end dashboard rendering ---

Write-Host ''
Write-Host ("nwa monitor - every {0}s ({1} pings/target) - {2}" -f $IntervalSec, $PingCount, $stopMsg) -ForegroundColor Green
if ($httpTargets.Count) { Write-Host ('Sites: ' + ($httpTargets -join ', ')) -ForegroundColor Green }
Write-Host ('Logging to: ' + $out) -ForegroundColor Green
Start-Sleep -Milliseconds 800

while (-not $stopReq -and ($DurationHours -le 0 -or (Get-Date) -lt $end)) {
  $tickStart = Get-Date
  $tick = [ordered]@{ t = $tickStart.ToString('o') }

  # connectivity: gateway (local hop) + internet IPs, each a burst of pings
  $q = [ordered]@{}
  if ($gateway) { $r = Test-PingSet $gateway $PingCount 1000; $q['gw'] = $r; $tick.gw = $(if ($r.recv) { $r.avg } else { -1 }) } else { $tick.gw = $null }
  foreach ($tg in $targets) { $r = Test-PingSet $tg $PingCount 1000; $q[$tg] = $r; $tick[$tg] = $(if ($r.recv) { $r.avg } else { -1 }) }
  $tick.q = $q

  # DNS resolution time (-DnsOnly: force a real query, not the local cache)
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  if ($script:hasResolve) { $rr = Resolve-DnsName -Name $dnsHost -Type A -DnsOnly -ErrorAction SilentlyContinue }
  else { $rr = $null; try { $rr = [System.Net.Dns]::GetHostAddresses($dnsHost) } catch {} }
  $sw.Stop()
  $tick.dns = $(if ($rr) { [int]$sw.Elapsed.TotalMilliseconds } else { -1 })

  # Wi-Fi link detail
  $w = Get-WlanInfo
  $tick.ssid=$w.ssid; $tick.sig=$w.sig; $tick.bssid=$w.bssid; $tick.band=$w.band; $tick.chan=$w.chan; $tick.rx=$w.rx; $tick.tx=$w.tx; $tick.radio=$w.radio

  # periodic channel-congestion scan
  if ($nbrEvery -gt 0 -and $w.chan -and ($k % $nbrEvery -eq 0)) { $tick.nbr = Get-Congestion $w.chan }
  $k++

  # adapters up + wired link speed ($null = could not enumerate; do not read that as "down")
  $allAd = @(Get-NetAdapter -ErrorAction SilentlyContinue)
  $ups = @($allAd | Where-Object { $_.Status -eq 'Up' })
  $tick.up = $(if ($allAd.Count -eq 0) { $null } else { [bool]$ups.Count })
  $eth = Get-EthMbps $ups
  if ($eth -ne $null) { $tick.eth = $eth }

  # Windows Wi-Fi events since last tick (disconnect reasons etc.)
  $wev = @(Get-WlanEvents $stLastEvT)
  $stLastEvT = $tickStart
  if ($wev.Count) { $tick.wlanEv = @($wev) }

  # sites (@() keeps a single result an array through ConvertTo-Json)
  if ($httpTargets.Count) { $tick.http = @(Test-Sites $httpTargets) } else { $tick.http = @() }

  # A full outage needs more evidence than ICMP alone: some networks block ping
  # while normal traffic keeps working. Only downgrade a ping failure when
  # something else actually crossed the internet in the same tick - an off-LAN
  # DNS answer, or a watched site responding. An on-prem resolver answering
  # proves nothing (it is reachable over the LAN during an internet outage).
  $reach = @($targets | ForEach-Object { $tick[$_] } | Where-Object { $_ -ge 0 }).Count
  $dnsProof  = $dnsIsPublic -and ($tick.dns -ge 0)
  $siteProof = [bool](@($tick.http | Where-Object { $_.ms -ge 0 }).Count)
  $isDown = ($tick.up -eq $false) -or (($reach -eq 0) -and -not $dnsProof -and -not $siteProof)
  $icmpOnly = ($reach -eq 0) -and -not $isDown
  $tick.down = [bool]$isDown
  $tick.icmpOnly = [bool]$icmpOnly
  if ($isDown -and -not $stWasDown -and ((Get-Date) - $stLastTrace).TotalSeconds -gt 300) {
    $tick.trace = @(Invoke-QuickTrace '1.1.1.1' 6)
    $stLastTrace = Get-Date
  }

  $tickEnd = Get-Date
  $tick.tEnd = $tickEnd.ToString('o')
  $tick.elapsedMs = [int][math]::Round(($tickEnd - $tickStart).TotalMilliseconds)
  $tickJson = $tick | ConvertTo-Json -Compress -Depth 6
  $script:logLines.Add($tickJson)
  Add-Content -Path $out -Value $tickJson -Encoding utf8

  # ---------- session stats + status ----------
  $i1 = $q['1.1.1.1']
  $loss = if ($i1) { $i1.loss } else { 100 }
  $jit  = if ($i1 -and $i1.jit -ne $null) { $i1.jit } else { 0 }
  if ($isDown) {
    if (-not $stWasDown) { $stOutages++; Add-Ev ($tickStart.ToString('HH:mm:ss') + ' DOWN') }
    $stDownSec += $IntervalSec
  } elseif ($stWasDown) { Add-Ev ($tickStart.ToString('HH:mm:ss') + ' back up') }
  $stWasDown = $isDown
  if (-not $isDown -and -not $icmpOnly -and $loss -gt 0) { $stLoss++ }
  if (-not $isDown -and $jit -ge 30) { $stJit++ }
  if ($tick.dns -lt 0) { $stDnsFail++; if (-not $isDown) { Add-Ev ($tickStart.ToString('HH:mm:ss') + ' DNS failed') } }
  if ($w.bssid) {
    if ($script:prevBssid -and $w.bssid -ne $script:prevBssid) { $stRoams++; Add-Ev ($tickStart.ToString('HH:mm:ss') + ' roamed to ' + $w.bssid) }
    [void]$stAps.Add($w.bssid)
    $script:prevBssid = $w.bssid
  }
  foreach ($e in $wev) { if ($e.id -eq 8003) { Add-Ev (([datetime]$e.t).ToString('HH:mm:ss') + ' ' + $e.msg) } }

  $state = if ($isDown) { 'DOWN' } elseif ($icmpOnly) { 'ICMP?' } elseif ($tick.dns -lt 0) { 'DNS!' } elseif ($loss -gt 0) { 'LOSS' } elseif ($jit -ge 30) { 'JIT' } else { 'ok' }
  $c = '.'; if ($state -eq 'DOWN') { $c = 'x' } elseif ($state -ne 'ok') { $c = '!' }
  $stHist += $c; if ($stHist.Length -gt 400) { $stHist = $stHist.Substring($stHist.Length - 400) }

  if ($interactive) {
    $sitesStr = '-'
    if ($tick.http.Count) { $sitesStr = (@($tick.http | ForEach-Object { $h=[System.Uri]$_.u; $h.Host + ' ' + $(if ($_.ms -lt 0) { 'DOWN' } else { [string]$_.ms + 'ms' }) }) -join '   ') }
    Draw-Dash @{
      hostName = $env:COMPUTERNAME
      interval = $IntervalSec
      elapsed = Format-Elapsed ((Get-Date) - $startT)
      n = $k
      state = $state
      ping = $(if ($tick.'1.1.1.1' -ge 0) { [string]$tick.'1.1.1.1' + ' ms' } else { '--' })
      loss = ([string]$loss + '%'); lossVal = $loss
      jit  = ([string]$jit + ' ms'); jitVal = $jit
      dns  = $(if ($tick.dns -ge 0) { [string]$tick.dns + ' ms' } else { 'FAIL' })
      gw   = $(if ($gateway) { $(if ($tick.gw -ge 0) { [string]$tick.gw + ' ms' } else { 'DOWN' }) } else { 'n/a' })
      wifi = ($w.sig -ne $null)
      ssid = $(if ($w.ssid) { $w.ssid } else { '-' })
      sig  = $(if ($w.sig -ne $null) { [string]$w.sig + '%' } else { '-' }); sigVal = $w.sig
      band = $(if ($w.band) { $w.band + '  ch' + $w.chan } else { '-' })
      rate = $(if ($w.rx -ne $null) { [string]$w.rx + ' Mbps' } else { '-' })
      link = $(if ($eth -ne $null) { 'wired  ' + $eth + ' Mbps' } else { 'no link' })
      ap   = $(if ($w.bssid) { $w.bssid } elseif ($bssidHidden) { 'hidden (Location off)' } else { '-' })
      roams = $stRoams; aps = $stAps.Count
      sites = $sitesStr
      hist = $stHist
      outages = [string]$stOutages; outagesN = $stOutages; downDur = ([string]$stDownSec + 's')
      lossN = [string]$stLoss; jitN = [string]$stJit; dnsN = [string]$stDnsFail
      events = @($stEvents)
      logPath = $out
    }
  } else {
    Write-Host ("[{0}] {1}  net={2}ms loss={3}% jit={4}ms  dns={5}ms  sig={6}% {7}" -f `
      $tickStart.ToString('HH:mm:ss'), $state.PadRight(4), $tick.'1.1.1.1', $loss, $jit, $tick.dns, $w.sig, $(if($w.band){$w.band}else{''}))
  }

  # wait for next tick, polling for Q
  $deadline = $tickStart.AddSeconds($IntervalSec)
  while ((Get-Date) -lt $deadline) {
    if ($interactive) {
      try {
        if ([Console]::KeyAvailable) {
          $key = [Console]::ReadKey($true)
          if ($key.Key -eq 'Q') { $stopReq = $true; break }
        }
      } catch {}
    }
    Start-Sleep -Milliseconds 150
  }
}

# ---------- wrap up ----------
Write-Host ''
Write-Host ('Stopped. ' + $k + ' samples over ' + (Format-Elapsed ((Get-Date) - $startT)) + '.') -ForegroundColor Green
Write-Host ('Log: ' + $out) -ForegroundColor Green

$doReport = [bool]$Report
if ($interactive -and -not $Report) {
  $ans = Read-Host 'Generate HTML report and open it? [Y/n]'
  if ($ans -eq '' -or $ans -match '^[yYjJ]') { $doReport = $true }
}
if ($doReport) { New-NwaReport @($script:logLines) $interactive $script:runId | Out-Null }
