# ============================================================
#  nwa - network diagnostics for Windows
#
#  Run it, watch the live status, press Q to stop - it builds
#  and opens an HTML report. The raw log (network-monitor.jsonl)
#  is written continuously, so nothing is lost on a crash.
#  Nothing is uploaded by this script; analysis is local.
#
#  Usage:
#    powershell -ep bypass -f .\nwa.ps1                    monitor until Q
#    powershell -ep bypass -f .\nwa.ps1 -Snapshot          one-shot check
#    powershell -ep bypass -f .\nwa.ps1 -Sites "a.com"     also test your sites
#
#  This file is generated by build.ps1 from src/nwa.src.ps1
#  plus index.html (the embedded report template). Edit src/,
#  then run build.ps1.
# ============================================================
param(
  [switch]$Snapshot,                 # one-shot health check instead of monitoring
  [string[]]$Sites = @(),            # extra sites to test, e.g. -Sites "yourapp.com","intranet.local"
  [int]$IntervalSec = 10,            # seconds between checks
  [double]$DurationHours = 0,        # 0 = run until Q / Ctrl+C
  [int]$PingCount = 5,               # pings per target per check (loss / jitter)
  [int]$NeighborScanSec = 300,       # how often to scan nearby APs (0 = never)
  [string]$OutDir = '',              # where files go (default: Desktop)
  [switch]$Report                    # always generate the report at the end (no prompt)
)

$ErrorActionPreference = 'SilentlyContinue'
$ProgressPreference    = 'SilentlyContinue'

# make sure the Windows networking modules (NetAdapter, DnsClient) are findable
$winMods = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\Modules'
if ((Test-Path $winMods) -and ($env:PSModulePath -notlike ('*' + $winMods + '*'))) { $env:PSModulePath += ';' + $winMods }
$script:hasResolve = [bool](Get-Command Resolve-DnsName -ErrorAction SilentlyContinue)

# Embedded report template: base64 of index.html from this repo (see build.ps1).
# It is only ever written to an .html file - never executed as code.
$NWA_B64 = '@@NWA_TEMPLATE_B64@@'

if (-not $OutDir) { $OutDir = [Environment]::GetFolderPath('Desktop') }
$targets = @('1.1.1.1','8.8.8.8')
$dnsHost = 'google.com'
$httpTargets = @(foreach ($s in $Sites) { $s = $s.Trim(); if ($s) { if ($s -match '^https?://') { $s } else { 'https://' + $s } } })

# ---------- helpers ----------

# fast multi-ping (no 1s gap) - returns recv/loss/min/avg/max/jitter
function Test-PingSet([string]$ip,[int]$count,[int]$timeoutMs){
  $rtts = New-Object System.Collections.Generic.List[int]
  $pinger = New-Object System.Net.NetworkInformation.Ping
  for ($i=0; $i -lt $count; $i++) {
    try { $pr = $pinger.Send($ip,$timeoutMs); if ($pr.Status -eq 'Success') { $rtts.Add([int]$pr.RoundtripTime) } } catch {}
  }
  $recv = $rtts.Count
  $o = [ordered]@{ recv=$recv; loss=[math]::Round((1-($recv/$count))*100,0); min=$null; avg=$null; max=$null; jit=$null }
  if ($recv -gt 0) {
    $o.min = ($rtts | Measure-Object -Minimum).Minimum
    $o.max = ($rtts | Measure-Object -Maximum).Maximum
    $o.avg = [math]::Round(($rtts | Measure-Object -Average).Average,0)
    if ($rtts.Count -gt 1) {
      $d = New-Object System.Collections.Generic.List[int]
      for ($i=1; $i -lt $rtts.Count; $i++) { $d.Add([math]::Abs($rtts[$i]-$rtts[$i-1])) }
      $o.jit = [math]::Round(($d | Measure-Object -Average).Average,0)
    } else { $o.jit = 0 }
  }
  return $o
}

# current Wi-Fi association (ssid, bssid, signal, band, channel, rates)
function Get-WlanInfo {
  $w = [ordered]@{ ssid=$null; sig=$null; bssid=$null; band=$null; chan=$null; rx=$null; tx=$null; radio=$null }
  foreach ($l in (netsh wlan show interfaces)) {
    if     ($l -match '^\s*SSID\s+:\s*(.+)$')                    { $w.ssid=$matches[1].Trim() }
    elseif ($l -match '^\s*Signal\s*:\s*(\d+)%')                 { $w.sig=[int]$matches[1] }
    elseif ($l -match 'BSSID\s*:\s*([0-9a-fA-F:]{17})')          { $w.bssid=$matches[1].Trim() }
    elseif ($l -match '^\s*Band\s*:\s*(.+)$')                    { $w.band=$matches[1].Trim() }
    elseif ($l -match '^\s*Channel\s*:\s*(\d+)')                 { $w.chan=[int]$matches[1] }
    elseif ($l -match '^\s*Receive rate \(Mbps\)\s*:\s*([\d\.]+)'){ $w.rx=[double]$matches[1] }
    elseif ($l -match '^\s*Transmit rate \(Mbps\)\s*:\s*([\d\.]+)'){ $w.tx=[double]$matches[1] }
    elseif ($l -match '^\s*Radio type\s*:\s*(.+)$')              { $w.radio=$matches[1].Trim() }
  }
  return $w
}

# scan nearby Wi-Fi networks -> how crowded is my channel
function Get-Congestion([int]$myChan){
  $chans = New-Object System.Collections.Generic.List[int]
  foreach ($l in (netsh wlan show networks mode=bssid)) {
    if ($l -match '^\s*Channel\s*:\s*(\d+)') { $chans.Add([int]$matches[1]) }
  }
  [ordered]@{ total = $chans.Count; coChan = @($chans | Where-Object { $_ -eq $myChan }).Count; chan = $myChan }
}

# new Windows Wi-Fi events since last check (connect / fail / disconnect + reason)
$script:wlanLogOk = $true
$script:wlanSeen  = New-Object System.Collections.Generic.HashSet[long]
function Get-WlanEvents([datetime]$since){
  if (-not $script:wlanLogOk) { return @() }
  $out = @()
  try {
    $evs = Get-WinEvent -FilterHashtable @{
      LogName='Microsoft-Windows-WLAN-AutoConfig/Operational'
      Id=@(8001,8002,8003)
      StartTime=$since.AddSeconds(-5)
    } -ErrorAction Stop
    foreach ($e in $evs) {
      if (-not $script:wlanSeen.Add([long]$e.RecordId)) { continue }
      $msg = ''
      if ($e.Id -eq 8003) {
        $msg = 'disconnect'
        if ($e.Message -match 'Reason:\s*(.+)') { $msg = 'disconnect: ' + $matches[1].Trim() }
      } elseif ($e.Id -eq 8001) { $msg = 'connected' }
      elseif ($e.Id -eq 8002)   { $msg = 'connection failed' }
      $out += [ordered]@{ t=$e.TimeCreated.ToString('o'); id=$e.Id; msg=$msg }
    }
    if ($script:wlanSeen.Count -gt 500) { $script:wlanSeen.Clear() }
  } catch {
    if ($_.FullyQualifiedErrorId -notmatch 'NoMatchingEvents') { $script:wlanLogOk = $false }
  }
  return @($out | Sort-Object t)
}

# short TTL-stepped trace: where does the path die? (bounded, ~4s worst case)
function Invoke-QuickTrace([string]$dest,[int]$maxHops){
  $hops = @()
  $p = New-Object System.Net.NetworkInformation.Ping
  $buf = New-Object byte[] 8
  for ($ttl=1; $ttl -le $maxHops; $ttl++) {
    try {
      $opt = New-Object System.Net.NetworkInformation.PingOptions($ttl,$true)
      $r = $p.Send($dest,700,$buf,$opt)
      if ($r.Status -eq 'Success')        { $hops += $r.Address.ToString(); break }
      elseif ($r.Status -eq 'TtlExpired') { $hops += $r.Address.ToString() }
      else                                { $hops += '*' }
    } catch { $hops += '*' }
  }
  return $hops
}

# wired adapter link speed in Mbps (catches 1000 -> 100 renegotiation)
function Get-EthMbps($upAdapters){
  $e = $upAdapters | Where-Object { $_.PhysicalMediaType -notmatch '802.11|Wireless' } | Select-Object -First 1
  if (-not $e) { return $null }
  if ($e.LinkSpeed -match '([\d\.]+)\s*(G|M)bps') {
    $v = [double]$matches[1]; if ($matches[2] -eq 'G') { $v = $v * 1000 }
    return [int]$v
  }
  return $null
}

# HTTP(S) reachability. ms = -1 means could not reach at all; any status code counts as reached.
function Test-Sites([string[]]$urls){
  @(foreach ($u in $urls) {
    $hsw = [System.Diagnostics.Stopwatch]::StartNew()
    try {
      $resp = Invoke-WebRequest -Uri $u -Method Head -TimeoutSec 6 -UseBasicParsing -ErrorAction Stop
      $hsw.Stop()
      [ordered]@{ u = $u; ms = [int]$hsw.Elapsed.TotalMilliseconds; code = [int]$resp.StatusCode }
    } catch {
      $hsw.Stop()
      $code = 0
      if ($_.Exception.Response) { try { $code = [int]$_.Exception.Response.StatusCode } catch {} }
      if ($code -gt 0) { [ordered]@{ u = $u; ms = [int]$hsw.Elapsed.TotalMilliseconds; code = $code } }
      else             { [ordered]@{ u = $u; ms = -1; code = 0 } }
    }
  })
}

# build network-report.html from a log file (data injected into the embedded template)
function New-NwaReport([string]$dataPath,[bool]$IsJsonl,[bool]$OpenIt){
  if ($NWA_B64 -like '@@*') { Write-Host 'No report template embedded (source build) - run build.ps1 first.' -ForegroundColor DarkYellow; return $null }
  try {
    $tpl = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($NWA_B64))
    if ($IsJsonl) { $arr = '[' + ((Get-Content $dataPath) -join ',') + ']' }
    else          { $arr = '[' + (Get-Content $dataPath -Raw) + ']' }
    $arr = $arr.Replace('</','<\/')   # keep '</script>' inside logged strings from breaking the page
    $html = $tpl.Replace('window.NWA_EMBEDDED = window.NWA_EMBEDDED || null;', 'window.NWA_EMBEDDED = ' + $arr + ';')
    $rp = Join-Path $OutDir 'network-report.html'
    Set-Content -Path $rp -Value $html -Encoding utf8
    Write-Host ('Report: ' + $rp) -ForegroundColor Green
    if ($OpenIt) { Start-Process $rp }
    return $rp
  } catch { Write-Host ('Could not build report: ' + $_) -ForegroundColor Red; return $null }
}

# ---------- environment context (collected once) ----------

$upIdx = @((Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }).ifIndex)
$dnsServers = @(Get-DnsClientServerAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
  Where-Object { $_.ServerAddresses -and ($upIdx -contains $_.InterfaceIndex) } |
  ForEach-Object { $_.ServerAddresses } | Select-Object -Unique)

$gateway = $null
try { $gateway = (Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway } | Select-Object -First 1).IPv4DefaultGateway.NextHop } catch {}
if ($gateway) {
  $gwTest = Test-PingSet $gateway 2 800
  if ($gwTest.recv -eq 0) { Write-Host "Gateway $gateway doesn't answer ping (ICMP blocked) - skipping gateway checks." -ForegroundColor DarkYellow; $gateway = $null }
}

# adapter + driver + power management (radio power saving is a common cause of drops)
$adapterInfo = $null
try {
  $a = Get-NetAdapter -ErrorAction Stop | Where-Object { $_.Status -eq 'Up' } |
       Sort-Object { if ($_.PhysicalMediaType -match '802.11|Wireless') { 0 } else { 1 } } | Select-Object -First 1
  if ($a) {
    $pm = $null
    try { $p = Get-NetAdapterPowerManagement -Name $a.Name -ErrorAction Stop
          if ($p) { $pm = [ordered]@{ selectiveSuspend = [string]$p.SelectiveSuspend; sleepOnDisconnect = [string]$p.DeviceSleepOnDisconnect } } } catch {}
    $adapterInfo = [ordered]@{
      name = $a.Name; description = $a.InterfaceDescription
      driverVersion = [string]$a.DriverVersion; driverDate = [string]$a.DriverDate
      linkSpeed = [string]$a.LinkSpeed; powerMgmt = $pm
    }
  }
} catch {}

# IPv6 reachability (context)
$ipv6 = $null
try { $r6 = Test-PingSet '2606:4700:4700::1111' 2 1200; $ipv6 = [ordered]@{ reachable = ($r6.recv -gt 0); ms = $r6.avg } }
catch { $ipv6 = [ordered]@{ reachable = $false; ms = $null } }

# Windows 11 24H2 hides BSSID / neighbor networks when Location is off
$w0 = Get-WlanInfo
$bssidHidden = $false
if ($w0.sig -ne $null -and -not $w0.bssid) {
  $bssidHidden = $true
  Write-Host 'Windows is hiding the AP identity (Location is off?) - roam detection will be limited.' -ForegroundColor DarkYellow
  Write-Host 'Enable Settings > Privacy & security > Location to get full Wi-Fi detail.' -ForegroundColor DarkYellow
}

# ============================================================
#  SNAPSHOT MODE
# ============================================================
if ($Snapshot) {
  $snapData = [ordered]@{}
  $snapData.schema      = 'nwa-report/1'
  $snapData.generatedAt = (Get-Date).ToString('o')
  $snapData.hoursWindow = 24

  Write-Host 'Collecting system info...'
  $os = Get-CimInstance Win32_OperatingSystem
  $snapData.system = [ordered]@{
    computerName = $env:COMPUTERNAME
    user         = $env:USERNAME
    os           = $os.Caption
    osVersion    = [string]$os.Version
    uptimeHours  = [math]::Round(((Get-Date) - $os.LastBootUpTime).TotalHours, 1)
  }

  Write-Host 'Collecting network adapters...'
  $snapData.adapters = @(Get-NetAdapter | ForEach-Object {
    [ordered]@{
      name        = $_.Name
      description = $_.InterfaceDescription
      status      = [string]$_.Status
      macAddress  = $_.MacAddress
      linkSpeed   = $_.LinkSpeed
      mediaType   = [string]$_.PhysicalMediaType
      ifIndex     = $_.ifIndex
    }
  })

  Write-Host 'Collecting IP configuration...'
  $snapData.ipConfig = @(Get-NetIPConfiguration | ForEach-Object {
    [ordered]@{
      alias   = $_.InterfaceAlias
      ipv4    = [string]$_.IPv4Address.IPAddress
      ipv6    = [string]$_.IPv6Address.IPAddress
      gateway = [string]$_.IPv4DefaultGateway.NextHop
    }
  })

  $snapData.dns = @(Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object { $_.ServerAddresses } | ForEach-Object {
    [ordered]@{ alias = $_.InterfaceAlias; servers = @($_.ServerAddresses) }
  })

  Write-Host 'Collecting adapter traffic counters...'
  $snapData.adapterStats = @(Get-NetAdapterStatistics | ForEach-Object {
    [ordered]@{
      name                   = $_.Name
      receivedBytes          = [int64]$_.ReceivedBytes
      sentBytes              = [int64]$_.SentBytes
      receivedUnicastPackets = [int64]$_.ReceivedUnicastPackets
      sentUnicastPackets     = [int64]$_.SentUnicastPackets
    }
  })

  Write-Host 'Collecting Wi-Fi state...'
  $snapData.wifi = [ordered]@{}
  $wifiRaw = netsh wlan show interfaces
  if ($wifiRaw) {
    $snapData.wifi.raw = ($wifiRaw -join "`n")
    foreach ($line in $wifiRaw) {
      if ($line -match '^\s*(SSID|BSSID|Signal|Channel|Band|Radio type|Receive rate \(Mbps\)|Transmit rate \(Mbps\)|Authentication|State)\s*:\s*(.+)$') {
        $snapData.wifi[$matches[1].Trim()] = $matches[2].Trim()
      }
    }
  }

  Write-Host 'Running latency tests...'
  $snapData.latency = @(foreach ($t in @('1.1.1.1','8.8.8.8','google.com')) {
    $r = Test-PingSet $t 4 1200
    [ordered]@{
      target   = $t
      sent     = 4
      received = $r.recv
      lossPct  = $r.loss
      avgMs    = $r.avg
      minMs    = $r.min
      maxMs    = $r.max
    }
  })

  Write-Host 'Testing DNS resolution speed...'
  $snapData.dnsTest = @(foreach ($h in @('google.com','cloudflare.com','microsoft.com')) {
    $sw  = [System.Diagnostics.Stopwatch]::StartNew()
    $res = Resolve-DnsName -Name $h -Type A -DnsOnly -ErrorAction SilentlyContinue
    $sw.Stop()
    [ordered]@{
      host      = $h
      ms        = [math]::Round($sw.Elapsed.TotalMilliseconds, 0)
      resolved  = [bool]$res
      addresses = @($res | Where-Object { $_.IPAddress } | ForEach-Object { $_.IPAddress })
    }
  })

  Write-Host 'Collecting active connections...'
  $procs = @{}
  Get-Process | ForEach-Object { $procs[$_.Id] = $_.ProcessName }
  $snapData.connections = @(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{
      localAddress  = $_.LocalAddress
      localPort     = $_.LocalPort
      remoteAddress = $_.RemoteAddress
      remotePort    = $_.RemotePort
      process       = $procs[[int]$_.OwningProcess]
      pid           = $_.OwningProcess
    }
  } | Select-Object -First 250)

  Write-Host 'Collecting listening ports...'
  $snapData.listening = @(Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{
      localAddress = $_.LocalAddress
      localPort    = $_.LocalPort
      process      = $procs[[int]$_.OwningProcess]
      pid          = $_.OwningProcess
    }
  } | Select-Object -First 150)

  $snapData.routes = @(Get-NetRoute -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue | ForEach-Object {
    [ordered]@{ ifAlias = $_.InterfaceAlias; nextHop = $_.NextHop; metric = $_.RouteMetric }
  })

  Write-Host 'Looking up public IP (best effort)...'
  try   { $snapData.publicIp = (Invoke-RestMethod -Uri 'https://api.ipify.org?format=json' -TimeoutSec 5).ip }
  catch { $snapData.publicIp = $null }

  Write-Host 'Collecting recent network events (last 24h)...'
  $since = (Get-Date).AddHours(-24)
  $snapData.events = @(Get-WinEvent -FilterHashtable @{ LogName = 'System'; StartTime = $since } -ErrorAction SilentlyContinue |
    Where-Object { $_.ProviderName -match 'Tcpip|Dhcp|WLAN|NetworkProfile|Netwtw|NDIS|Wlansvc|Dnscache' } |
    Select-Object -First 300 | ForEach-Object {
      [ordered]@{
        time     = $_.TimeCreated.ToString('o')
        level    = [string]$_.LevelDisplayName
        provider = $_.ProviderName
        id       = $_.Id
        message  = ($_.Message -replace '\s+', ' ').Trim()
      }
    })

  $outPath = Join-Path $OutDir 'network-report.json'
  $snapData | ConvertTo-Json -Depth 8 | Out-File -FilePath $outPath -Encoding utf8
  Write-Host ('Data: ' + $outPath) -ForegroundColor Green
  $interactive = $true
  try { $interactive = ($Host.Name -eq 'ConsoleHost') -and -not [Console]::IsInputRedirected } catch { $interactive = $false }
  New-NwaReport $outPath $false ($interactive -or $Report) | Out-Null
  return
}

# ============================================================
#  MONITOR MODE
# ============================================================
$out = Join-Path $OutDir 'network-monitor.jsonl'

$meta = [ordered]@{
  schema          = 'nwa-monitor/1'
  startedAt       = (Get-Date).ToString('o')
  intervalSec     = $IntervalSec
  durationHours   = $DurationHours
  pingCount       = $PingCount
  neighborScanSec = $NeighborScanSec
  computerName    = $env:COMPUTERNAME
  targets         = $targets
  gateway         = $gateway
  dnsHost         = $dnsHost
  dnsServers      = $dnsServers
  adapter         = $adapterInfo
  ipv6            = $ipv6
  bssidHidden     = $bssidHidden
  httpTargets     = $httpTargets
}
Set-Content -Path $out -Value ($meta | ConvertTo-Json -Compress) -Encoding utf8

$interactive = $true
try { $interactive = ($Host.Name -eq 'ConsoleHost') -and -not [Console]::IsInputRedirected } catch { $interactive = $false }

$end = (Get-Date).AddHours($DurationHours)
$stopMsg = if ($DurationHours -le 0) { 'until you press Q' } else { "until $end (or Q)" }
if (-not $interactive) { $stopMsg = if ($DurationHours -le 0) { 'until Ctrl+C' } else { "until $end" } }

# ---------- session state ----------
$nbrEvery  = if ($NeighborScanSec -gt 0) { [math]::Max(1, [int]($NeighborScanSec / $IntervalSec)) } else { 0 }
$k = 0
$stopReq = $false
$startT = Get-Date
$stLastEvT = Get-Date
$stRoams = 0; $stAps = New-Object System.Collections.Generic.HashSet[string]
$stOutages = 0; $stDownSec = 0; $stWasDown = $false
$stLoss = 0; $stJit = 0; $stDnsFail = 0
$stLastEvent = '-'
$stHist = ''
$stLastTrace = [datetime]::MinValue
$script:dashDrawn = $false

function Format-Elapsed([timespan]$ts){
  if ($ts.TotalHours -ge 1) { return ('{0}h {1:d2}m' -f [int][math]::Floor($ts.TotalHours), $ts.Minutes) }
  return ('{0:d2}:{1:d2}' -f $ts.Minutes, $ts.Seconds)
}

function Draw-Dash($d){
  $w = 78
  try { $w = [math]::Min(110, [math]::Max(64, [Console]::WindowWidth - 1)) } catch {}
  try {
    if (-not $script:dashDrawn) { Clear-Host; $script:dashDrawn = $true }
    [Console]::SetCursorPosition(0,0)
  } catch { $script:dashDrawn = $true }
  $pad = { param($s) $s = [string]$s; if ($s.Length -gt $w) { $s.Substring(0,$w) } else { $s.PadRight($w) } }

  Write-Host (& $pad (' NWA MONITOR   ' + $env:COMPUTERNAME + '   ' + $d.elapsed + '   ' + $d.n + ' samples   [Q] stop + report')) -ForegroundColor Cyan
  Write-Host (& $pad (' ' + ('-' * ($w-2))))
  $stCol = 'Green'; if ($d.state -eq 'DOWN') { $stCol = 'Red' } elseif ($d.state -ne 'ok') { $stCol = 'Yellow' }
  Write-Host (' net    ') -NoNewline
  Write-Host ($d.state.PadRight(6)) -NoNewline -ForegroundColor $stCol
  Write-Host (& $pad ('ping ' + $d.ping + '   loss ' + $d.loss + '   jitter ' + $d.jit + '   dns ' + $d.dns)).Substring(0,$w-14)
  Write-Host (& $pad (' link   ' + $d.link))
  Write-Host (& $pad (' ap     ' + $d.ap + '   roams ' + $d.roams + '   aps seen ' + $d.aps))
  Write-Host (& $pad (' sites  ' + $d.sites))
  Write-Host (& $pad (' hist   [' + $d.hist + ']   . ok  ! degraded  x down'))
  Write-Host (& $pad (' total  outages ' + $d.outages + ' (' + $d.downDur + ')   loss ticks ' + $d.lossN + '   jit>=30 ' + $d.jitN + '   dns fails ' + $d.dnsN))
  Write-Host (& $pad (' event  ' + $d.lastEvent)) -ForegroundColor DarkGray
  Write-Host (& $pad (' log    ' + $d.logPath)) -ForegroundColor DarkGray
}

Write-Host ''
Write-Host ("nwa monitor - every {0}s ({1} pings/target) - {2}" -f $IntervalSec, $PingCount, $stopMsg) -ForegroundColor Green
if ($httpTargets.Count) { Write-Host ('Sites: ' + ($httpTargets -join ', ')) -ForegroundColor Green }
Write-Host ('Logging to: ' + $out) -ForegroundColor Green
Start-Sleep -Milliseconds 800

while (-not $stopReq -and ($DurationHours -le 0 -or (Get-Date) -lt $end)) {
  $tickStart = Get-Date
  $tick = [ordered]@{ t = $tickStart.ToString('o') }

  # connectivity: gateway (local hop) + internet IPs, each a burst of pings
  $q = [ordered]@{}
  if ($gateway) { $r = Test-PingSet $gateway $PingCount 1000; $q['gw'] = $r; $tick.gw = $(if ($r.recv) { $r.avg } else { -1 }) } else { $tick.gw = $null }
  foreach ($tg in $targets) { $r = Test-PingSet $tg $PingCount 1000; $q[$tg] = $r; $tick[$tg] = $(if ($r.recv) { $r.avg } else { -1 }) }
  $tick.q = $q

  # DNS resolution time (-DnsOnly: force a real query, not the local cache)
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  if ($script:hasResolve) { $rr = Resolve-DnsName -Name $dnsHost -Type A -DnsOnly -ErrorAction SilentlyContinue }
  else { $rr = $null; try { $rr = [System.Net.Dns]::GetHostAddresses($dnsHost) } catch {} }
  $sw.Stop()
  $tick.dns = $(if ($rr) { [int]$sw.Elapsed.TotalMilliseconds } else { -1 })

  # Wi-Fi link detail
  $w = Get-WlanInfo
  $tick.ssid=$w.ssid; $tick.sig=$w.sig; $tick.bssid=$w.bssid; $tick.band=$w.band; $tick.chan=$w.chan; $tick.rx=$w.rx; $tick.tx=$w.tx; $tick.radio=$w.radio

  # periodic channel-congestion scan
  if ($nbrEvery -gt 0 -and $w.chan -and ($k % $nbrEvery -eq 0)) { $tick.nbr = Get-Congestion $w.chan }
  $k++

  # adapters up + wired link speed ($null = could not enumerate; do not read that as "down")
  $allAd = @(Get-NetAdapter -ErrorAction SilentlyContinue)
  $ups = @($allAd | Where-Object { $_.Status -eq 'Up' })
  $tick.up = $(if ($allAd.Count -eq 0) { $null } else { [bool]$ups.Count })
  $eth = Get-EthMbps $ups
  if ($eth -ne $null) { $tick.eth = $eth }

  # Windows Wi-Fi events since last tick (disconnect reasons etc.)
  $wev = @(Get-WlanEvents $stLastEvT)
  $stLastEvT = $tickStart
  if ($wev.Count) { $tick.wlanEv = @($wev) }

  # sites (@() keeps a single result an array through ConvertTo-Json)
  if ($httpTargets.Count) { $tick.http = @(Test-Sites $httpTargets) } else { $tick.http = @() }

  # down detection + trace on transition (rate-limited)
  $reach = @($targets | ForEach-Object { $tick[$_] } | Where-Object { $_ -ge 0 }).Count
  $isDown = ($tick.up -eq $false) -or ($reach -eq 0)
  if ($isDown -and -not $stWasDown -and ((Get-Date) - $stLastTrace).TotalSeconds -gt 300) {
    $tick.trace = @(Invoke-QuickTrace '1.1.1.1' 6)
    $stLastTrace = Get-Date
  }

  Add-Content -Path $out -Value ($tick | ConvertTo-Json -Compress -Depth 6) -Encoding utf8

  # ---------- session stats + status ----------
  $i1 = $q['1.1.1.1']
  $loss = if ($i1) { $i1.loss } else { 100 }
  $jit  = if ($i1 -and $i1.jit -ne $null) { $i1.jit } else { 0 }
  if ($isDown) {
    if (-not $stWasDown) { $stOutages++; $stLastEvent = $tickStart.ToString('HH:mm:ss') + ' DOWN' }
    $stDownSec += $IntervalSec
  } elseif ($stWasDown) { $stLastEvent = $tickStart.ToString('HH:mm:ss') + ' back up' }
  $stWasDown = $isDown
  if (-not $isDown -and $loss -gt 0) { $stLoss++ }
  if (-not $isDown -and $jit -ge 30) { $stJit++ }
  if ($tick.dns -lt 0) { $stDnsFail++; if (-not $isDown) { $stLastEvent = $tickStart.ToString('HH:mm:ss') + ' DNS failed' } }
  if ($w.bssid) {
    if ($script:prevBssid -and $w.bssid -ne $script:prevBssid) { $stRoams++; $stLastEvent = $tickStart.ToString('HH:mm:ss') + ' roamed to ' + $w.bssid }
    [void]$stAps.Add($w.bssid)
    $script:prevBssid = $w.bssid
  }
  foreach ($e in $wev) { if ($e.id -eq 8003) { $stLastEvent = ([datetime]$e.t).ToString('HH:mm:ss') + ' ' + $e.msg } }

  $state = if ($isDown) { 'DOWN' } elseif ($tick.dns -lt 0) { 'DNS!' } elseif ($loss -gt 0) { 'LOSS' } elseif ($jit -ge 30) { 'JIT' } else { 'ok' }
  $c = '.'; if ($state -eq 'DOWN') { $c = 'x' } elseif ($state -ne 'ok') { $c = '!' }
  $stHist += $c; if ($stHist.Length -gt 400) { $stHist = $stHist.Substring($stHist.Length - 400) }

  if ($interactive) {
    $linkStr = 'no link'
    if ($w.sig -ne $null) { $linkStr = ('{0}  {1} ch{2}  sig {3}%  rate {4} Mbps' -f $w.ssid, $w.band, $w.chan, $w.sig, $w.rx) }
    elseif ($eth -ne $null) { $linkStr = ('wired  {0} Mbps' -f $eth) }
    $sitesStr = '-'
    if ($tick.http.Count) { $sitesStr = (@($tick.http | ForEach-Object { $h=[System.Uri]$_.u; $h.Host + ' ' + $(if ($_.ms -lt 0) { 'DOWN' } else { [string]$_.ms + 'ms' }) }) -join '   ') }
    $histW = 44; try { $histW = [math]::Max(30,[math]::Min(80,[Console]::WindowWidth - 30)) } catch {}
    Draw-Dash @{
      elapsed = Format-Elapsed ((Get-Date) - $startT)
      n = $k
      state = $state
      ping = $(if ($tick.'1.1.1.1' -ge 0) { [string]$tick.'1.1.1.1' + ' ms' } else { '--' })
      loss = ([string]$loss + '%')
      jit  = ([string]$jit + ' ms')
      dns  = $(if ($tick.dns -ge 0) { [string]$tick.dns + ' ms' } else { 'FAIL' })
      link = $linkStr
      ap   = $(if ($w.bssid) { $w.bssid } elseif ($bssidHidden) { 'hidden (Location off)' } else { '-' })
      roams = $stRoams; aps = $stAps.Count
      sites = $sitesStr
      hist = $stHist.Substring([math]::Max(0,$stHist.Length - $histW))
      outages = $stOutages; downDur = ([string]$stDownSec + 's')
      lossN = $stLoss; jitN = $stJit; dnsN = $stDnsFail
      lastEvent = $stLastEvent
      logPath = $out
    }
  } else {
    Write-Host ("[{0}] {1}  net={2}ms loss={3}% jit={4}ms  dns={5}ms  sig={6}% {7}" -f `
      $tickStart.ToString('HH:mm:ss'), $state.PadRight(4), $tick.'1.1.1.1', $loss, $jit, $tick.dns, $w.sig, $(if($w.band){$w.band}else{''}))
  }

  # wait for next tick, polling for Q
  $deadline = $tickStart.AddSeconds($IntervalSec)
  while ((Get-Date) -lt $deadline) {
    if ($interactive) {
      try {
        if ([Console]::KeyAvailable) {
          $key = [Console]::ReadKey($true)
          if ($key.Key -eq 'Q') { $stopReq = $true; break }
        }
      } catch {}
    }
    Start-Sleep -Milliseconds 150
  }
}

# ---------- wrap up ----------
Write-Host ''
Write-Host ('Stopped. ' + $k + ' samples over ' + (Format-Elapsed ((Get-Date) - $startT)) + '.') -ForegroundColor Green
Write-Host ('Log: ' + $out) -ForegroundColor Green

$doReport = [bool]$Report
if ($interactive -and -not $Report) {
  $ans = Read-Host 'Generate HTML report and open it? [Y/n]'
  if ($ans -eq '' -or $ans -match '^[yYjJ]') { $doReport = $true }
}
if ($doReport) { New-NwaReport $out $true $interactive | Out-Null }
